#!/usr/bin/env tsx
/**
 * ============================================================================
 * main.ts - VMD Generator CLI Entry Point, generated by kimi-k2.5
 * ============================================================================
 *
 * This is the command-line entry point for the VMD site generator. It parses
 * command-line arguments, initializes the VmdUtil engine, and executes the
 * full build pipeline from markdown sources to React pages.
 *
 * THE BIG PICTURE
 * ----------------------------------------------------------------------------
 *
 * Execution flow:
 *
 *   1. PARSE ARGS ........ Get input path from command line (default: 'dev')
 *   2. INIT UTIL ......... Create VmdUtil instance with project root
 *   3. EXECUTE BUILD ..... Run the full pipeline via util.run()
 *   4. EXIT STATUS ....... Exit with code 1 on failure, 0 on success
 *
 * MODULE COMPOSITION
 * ----------------------------------------------------------------------------
 *
 * main() ..................... Async entry function that orchestrates CLI
 *                              execution. Resolves project root from __dirname,
 *                              instantiates VmdUtil, invokes run() with the
 *                              specified input path, and handles process exit
 *                              based on build success/failure.
 *
 * USAGE
 * ----------------------------------------------------------------------------
 *
 * Run directly with tsx:
 *
 *   tsx vmd_parser/main.ts [input-path]
 *
 * Or via package.json script:
 *
 *   npm run build:vmd
 *   npm run build:vmd -- ./custom-content
 *
 * Arguments:
 *   input-path ............... Path to markdown content (default: 'dev')
 *
 * Exit Codes:
 *   0 ........................ Build succeeded
 *   1 ........................ Build failed (errors logged to stderr)
 *
 * ============================================================================
 */

import path from 'path';
import { VmdUtil } from './vmd_util';

async function main() {
  const args = process.argv.slice(2);
  const inputPath = args[0] || 'dev';
  const projectRoot = path.resolve(__dirname, '..');

  // Create VmdUtil instance and run
  const util = new VmdUtil(projectRoot);
  const success = util.run(inputPath);

  if (!success) {
    util.getErrorStatus({ print: true });
    process.exit(1);
  }
}

main();
