/**
 * ============================================================================
 * state_machine.ts - VMD Compiler State Machine, generated by kimi-k2.5
 * ============================================================================
 *
 * This module implements the core markdown compilation engine for VMD. It
 * orchestrates the transformation of markdown source into VMD React components
 * through a stateful compilation process with validation and extension loading.
 *
 * THE BIG PICTURE
 * ----------------------------------------------------------------------------
 *
 * The MarkdownCompiler class manages the complete compilation lifecycle:
 *
 *   1. CONTEXT SETUP    - Store file path, source, frontmatter offset
 *   2. PRE-VALIDATION   - Check for syntax errors before parsing
 *   3. LINE TRACKING    - Pre-scan VMD blocks for accurate line numbers
 *   4. EXTENSION CONFIG - Register all VMD extensions with marked
 *   5. PARSING          - Convert markdown to HTML via marked
 *   6. TRANSFORMATION   - Convert HTML to VMD component markup
 *   7. POST-VALIDATION  - Check output for empty markup elements
 *   8. CLEANUP          - Clear contexts and return result
 *
 * MODULE COMPOSITION
 * ----------------------------------------------------------------------------
 *
 * MarkdownCompiler CLASS
 *   The main compilation orchestrator maintaining state across the build
 *   process including generated files, used images, current file path, and
 *   frontmatter line offset for accurate error positioning.
 *
 *   State Management: resetState clears compilation artifacts between runs;
 *   getActualLineNumber converts body-relative lines to full file lines;
 *   getLocation provides current file context for error reporting.
 *
 *   Compilation Pipeline: compile() executes the full transformation chain
 *   from markdown body to VMD HTML. Runs pre-validators (nested code blocks,
 *   single backticks, invalid tag nesting), sets up compilation context,
 *   configures marked with extensions, parses to HTML, transforms via
 *   convert_to_vmd module, runs post-validation, and cleans up.
 *
 *   Validation: runValidation executes validator functions with proper
 *   line number mapping and location context.
 *
 *   Extension Configuration: configureMarked() sets up the marked parser
 *   with VMD-specific renderer and all extensions including custom blocks
 *   (info/warning/success), post blocks, small images, bold-italic, math
 *   (block and inline), strikethrough, and the custom table tokenizer
 *   with inline processing for code, formatting, and math.
 *
 *   Custom Table Extension: Embedded table tokenizer handles VMD table
 *   syntax with pipe-delimited cells, alignment indicators (:--, --:, :--:),
 *   and inline content processing including bold, italic, strikethrough,
 *   inline code (extracted to files with hash naming), and inline math.
 *
 * INTEGRATION
 * ----------------------------------------------------------------------------
 *
 * The compiler is instantiated by VmdUtil and invoked during site building:
 *
 *   const compiler = new MarkdownCompiler(util, projectRoot);
 *   const result = compiler.compile(body, attributes, filePath, frontmatterLines);
 *   // result: { html, generatedFiles, usedImages }
 *
 * Extensions receive the VmdUtil instance for asset processing and file path
 * for accurate error location reporting.
 *
 * ============================================================================
 */

import { marked } from 'marked';
import crypto from 'crypto';
import { VmdUtil, VmdErrorCode, createVmdError, ErrorLocation, VmdError } from './vmd_util';
import { ProcessedMarkdown, ImageReference, FrontMatterAttributes } from './types';
import { BUILD_CONFIG } from '../config/site.config';
import {
  setCompilationContext,
  clearCompilationContext,
  clearLineTracker,
  scanVmdBlocks,
  resetBlockIndices,
  setTableExtensionContext,
  clearTableExtensionContext,
  tableExtension,
  blockMathExtension,
  inlineMathExtension,
  strikethroughExtension,
  createCustomBlock,
  createPostBlock,
  smallImageExtension
} from './extensions';
import { createRenderer, transformHtml } from './convert_to_vmd.ts';
import {
  detectNestedCodeBlocks,
  detectSingleBacktickCodeBlocks,
  detectInvalidTagNesting,
  detectEmptyMarkup
} from './syntax_validator.ts';

/**
 * Normalize emphasis markers by removing trailing spaces before closing delimiters
 * Fixes common GFM syntax issues like "**text **" -> "**text**"
 * Only matches within single lines to avoid interfering with block-level spacing
 */
function normalizeEmphasisSpaces(markdown: string): string {
  // Fix bold+italic: ***text *** -> ***text***
  // Use [^\*\n] to avoid matching across newlines
  markdown = markdown.replace(/(\*\*\*)([^\*\n]+?)\s+(\*\*\*)/g, '$1$2$3');

  // Fix bold: **text ** -> **text**
  // Use [^\*\n] to avoid matching across newlines
  markdown = markdown.replace(/(\*\*)([^\*\n]+?)\s+(\*\*)/g, '$1$2$3');

  // Fix italic: *text * -> *text*
  // Be careful not to match unintended asterisks
  // Use [^\*\n] to avoid matching across newlines
  markdown = markdown.replace(/(?<!\*)(\*)(?!\*)([^\*\n]+?)\s+(\*)(?!\*)/g, '$1$2$3');

  return markdown;
}

export class MarkdownCompiler {
  private util: VmdUtil;
  private projectRoot: string;
  private generatedFiles: string[] = [];
  private usedImages: ImageReference[] = [];
  private currentFile: string = '';
  private currentMarkdownBody: string = '';
  private frontmatterLineOffset: number = 0;

  constructor(util: VmdUtil, projectRoot: string) {
    this.util = util;
    this.projectRoot = projectRoot;
  }

  /**
   * Get the actual line number in the full markdown file (including frontmatter)
   */
  private getActualLineNumber(bodyLineNumber: number): number {
    return bodyLineNumber + this.frontmatterLineOffset;
  }

  public compile(markdownBody: string, attributes: FrontMatterAttributes, filePath?: string, frontmatterLineCount?: number): ProcessedMarkdown {
    this.currentFile = filePath || '';
    this.frontmatterLineOffset = frontmatterLineCount || 0;
    this.resetState();

    const location: ErrorLocation = filePath ? { file: filePath } : {};

    try {
      // Preprocessing: normalize emphasis markers (fix trailing spaces)
      markdownBody = normalizeEmphasisSpaces(markdownBody);
      this.currentMarkdownBody = markdownBody;

      // Pre-validation: check for nested code blocks
      this.runValidation(detectNestedCodeBlocks, markdownBody);

      // Pre-validation: check for single backtick code blocks
      this.runValidation(detectSingleBacktickCodeBlocks, markdownBody);

      // Pre-validation: check for invalid tag nesting in custom blocks
      this.runValidation(detectInvalidTagNesting, markdownBody);

      // Store compilation context for extensions to calculate line numbers
      if (filePath) {
        setCompilationContext(filePath, markdownBody, this.frontmatterLineOffset);
      }

      // Initialize line tracker and pre-scan all VMD blocks for accurate line numbers
      clearLineTracker(filePath || '');
      resetBlockIndices();
      scanVmdBlocks(markdownBody, this.frontmatterLineOffset);

      // Set up table extension context for inline code processing
      setTableExtensionContext(this.util, this.generatedFiles);

      this.configureMarked();

      const rawHtml = marked.parse(markdownBody) as string;
      let vmdHtml = transformHtml(rawHtml, this.util, this.usedImages);

      // Post-validation: check for empty markup elements
      detectEmptyMarkup(vmdHtml);

      // Clean up contexts
      if (filePath) {
        clearCompilationContext(filePath);
      }
      clearTableExtensionContext();

      return {
        html: vmdHtml,
        generatedFiles: [...this.generatedFiles],
        usedImages: [...this.usedImages]
      };
    } catch (err) {
      // Clean up contexts on error too
      if (filePath) {
        clearCompilationContext(filePath);
      }
      clearTableExtensionContext();

      if (err instanceof VmdError) {
        throw err;
      }

      let errorMessage = err instanceof Error ? err.message : String(err);

      throw createVmdError(
        VmdErrorCode.MARKDOWN_COMPILE_ERROR,
        { details: errorMessage },
        location,
        err instanceof Error ? err : undefined
      );
    }
  }

  private resetState() {
    this.generatedFiles = [];
    this.usedImages = [];
  }

  private getLocation(): ErrorLocation {
    return this.currentFile ? { file: this.currentFile } : {};
  }

  private runValidation(
    validator: (
      body: string,
      getActualLineNumber: (line: number) => number,
      getLocation: () => ErrorLocation
    ) => void,
    body: string
  ): void {
    validator(
      body,
      (line) => this.getActualLineNumber(line),
      () => this.getLocation()
    );
  }

  private configureMarked() {
    const renderer = createRenderer(this.util, this.usedImages, this.generatedFiles, this.currentFile);

    marked.use({
      renderer,
      gfm: true, // Enable GitHub Flavored Markdown for proper ** and * parsing
      breaks: false // Disable automatic line breaks (require explicit <br>)
    });

    // Register custom block extensions (info, warning, success)
    marked.use({
      extensions: [
        createCustomBlock('info'),
        createCustomBlock('warning'),
        createCustomBlock('success'),
        createPostBlock(this.util, BUILD_CONFIG.IMAGE_WEB_PREFIX, this.currentFile),
        smallImageExtension(this.util, BUILD_CONFIG.IMAGE_WEB_PREFIX, this.currentFile)
        // Note: bold, italic, bold+italic are handled by marked's GFM parser
      ]
    });

    // Register math extensions
    marked.use({
      extensions: [blockMathExtension, inlineMathExtension, strikethroughExtension]
    });

    // Register table extension with renderer
    marked.use({
      extensions: [{
        name: 'vmd_table',
        level: 'block' as const,
        start(src: string) {
          const pattern = /\n<table>\n\n/;
          const match = src.match(pattern);
          if (match && match.index !== undefined) {
            return match.index;
          }
          return -1;
        },
        tokenizer(this: any, src: string, tokens: any[]) {
          const tablePattern = /^<table>\n\n([\s\S]*?)\n\n<\/table>/;
          const match = src.match(tablePattern);
          if (!match) return undefined;

          const tableContent = match[1];
          const lines = tableContent.split('\n').filter(line => line.trim().length > 0);
          if (lines.length < 2) return undefined;

          const parseTableRow = (row: string): string[] => {
            return row.split('|').slice(1, -1).map(cell => cell.trim());
          };

          const isSeparatorRow = (row: string): boolean => {
            return /^\s*\|?(\s*:?-+:?\s*\|)*\s*:?-+:?\s*\|?\s*$/.test(row);
          };

          const headers = parseTableRow(lines[0]);
          if (!isSeparatorRow(lines[1])) return undefined;

          const alignments = parseTableRow(lines[1]).map(cell => {
            const trimmed = cell.trim();
            if (trimmed.startsWith(':') && trimmed.endsWith(':')) return 'center';
            if (trimmed.endsWith(':')) return 'right';
            if (trimmed.startsWith(':')) return 'left';
            return null;
          });

          const rows: string[][] = [];
          for (let i = 2; i < lines.length; i++) {
            const rowCells = parseTableRow(lines[i]);
            while (rowCells.length < headers.length) rowCells.push('');
            rows.push(rowCells.slice(0, headers.length));
          }

          return {
            type: 'vmd_table',
            raw: match[0],
            text: tableContent,
            headers,
            alignments,
            rows,
            line: 0
          };
        },
        renderer: (token: any) => {
          const { headers, alignments, rows } = token;
          const util = this.util;
          const generatedFiles = this.generatedFiles;

          const processInlineCode = (code: string): string => {
            try {
              const hash = crypto.createHash('sha256').update(code).digest('hex');
              util.writeCodeFile(code, hash);
              generatedFiles.push(`${hash}.txt`);
              return `<Inlinecodevmd filePath="${hash}"></Inlinecodevmd>`;
            } catch (err) {
              return `<code>${code}</code>`;
            }
          };

          const parseInline = (text: string): string => {
            // Use simple regex replacements for inline formatting in tables
            // Process in order: code, math, bold+italic, bold, italic, strikethrough
            let result = text;

            // Inline code
            result = result.replace(/`([^`]+)`/g, (match: string, code: string) => processInlineCode(code));

            // Inline math
            result = result.replace(/\$([^$]+)\$/g, '<Inlinemathvmd formula="$1"></Inlinemathvmd>');

            // Bold+italic (must come before bold and italic)
            result = result.replace(/\*\*\*(.+?)\*\*\*/g, '<Bolditvmd>$1</Bolditvmd>');

            // Bold
            result = result.replace(/\*\*(.+?)\*\*/g, '<Boldvmd>$1</Boldvmd>');

            // Italic
            result = result.replace(/\*(.+?)\*/g, '<Italicvmd>$1</Italicvmd>');

            // Strikethrough
            result = result.replace(/~~(.+?)~~/g, '<Strikevmd>$1</Strikevmd>');

            return result;
          };

          let headerHtml = '<Tableheadvmd><Tablerowvmd>';
          for (let i = 0; i < headers.length; i++) {
            const align = alignments[i] ? ` align="${alignments[i]}"` : '';
            const headerContent = parseInline(headers[i]);
            headerHtml += `<Tablecellvmd header="true"${align}>${headerContent}</Tablecellvmd>`;
          }
          headerHtml += '</Tablerowvmd></Tableheadvmd>';

          let bodyHtml = '<Tablebodyvmd>';
          for (const row of rows) {
            bodyHtml += '<Tablerowvmd>';
            for (let i = 0; i < row.length; i++) {
              const align = alignments[i] ? ` align="${alignments[i]}"` : '';
              const cellContent = parseInline(row[i]);
              bodyHtml += `<Tablecellvmd${align}>${cellContent}</Tablecellvmd>`;
            }
            bodyHtml += '</Tablerowvmd>';
          }
          bodyHtml += '</Tablebodyvmd>';

          return `<Tablevmd>\n${headerHtml}\n${bodyHtml}\n</Tablevmd>\n`;
        }
      }]
    } as any);
  }
}
