/**
 * ============================================================================
 * syntax_validator.ts - VMD Syntax Validation Engine, generated by kimi-k2.5
 * ============================================================================
 *
 * This module provides comprehensive syntax validation for VMD markdown
 * content. It detects structural errors, invalid nesting, and malformed
 * syntax before and during compilation with precise line number reporting.
 *
 * THE BIG PICTURE
 * ----------------------------------------------------------------------------
 *
 * Validation operates at multiple stages:
 *
 *   PRE-COMPILATION ...... Detect syntax errors before marked parses
 *   LINE TRACKING ........ Map positions to actual file lines
 *   CONTEXT MANAGEMENT ... Track compilation state per file
 *   BLOCK SCANNING ....... Pre-scan VMD blocks for accurate positions
 *
 * MODULE COMPOSITION
 * ----------------------------------------------------------------------------
 *
 * LINE TRACKING SYSTEM
 *   clearLineTracker ......... Reset tracker for new file compilation
 *   scanVmdBlocks ............ Pre-scan markdown to record all <post>
 *                              block positions with line numbers
 *   getBlockLineNumber ....... Get next post block line in sequence
 *   resetBlockIndices ........ Reset counter before tokenization
 *   calculateSubContentLine .. Calculate line for nested content
 *   debugPrintTrackedBlocks .. Debug output of tracked positions
 *
 * COMPILATION CONTEXT
 *   setCompilationContext .... Store file source and frontmatter offset
 *   clearCompilationContext .. Remove context for completed file
 *   getMarkdownSource ........ Retrieve stored source by file path
 *   getFrontmatterLineCount .. Get stored frontmatter line count
 *   hasCompilationContext .... Check if context exists for file
 *   getFileLocation .......... Build ErrorLocation from context
 *   getLineAtPosition ........ Calculate line number at position
 *
 * POSITION HELPERS
 *   isPositionInCode ......... Detect if position is inside code block
 *                              (fenced or inline), used by extensions
 *                              to skip processing inside code
 *
 * VALIDATION DETECTORS
 *   detectNestedCodeBlocks ... Find code blocks inside code blocks
 *   detectSingleBacktickCodeBlocks Find single-backtick code fences
 *   detectInvalidTagNesting .. Check protected tags inside containers
 *   detectEmptyMarkup ........ Find empty HTML elements in output
 *
 * TABLE EXTENSION CONTEXT
 *   setTableExtensionContext . Store util and files for table processing
 *   clearTableExtensionContext Clean up after compilation
 *   getTableExtensionContext . Retrieve current context
 *
 * TABLE EXTENSION
 *   tableExtension ........... Marked extension for VMD tables with
 *                              custom tokenizer validating structure
 *                              and renderer outputting Tablevmd components
 *
 * CONSTANTS
 *   PROTECTED_TAGS ........... Tags that cannot be nested (post, lft, rt)
 *   POST_ONLY_TAGS ........... Tags only allowed inside post (lft, rt)
 *   CONTAINER_TAGS ........... Blocks that cannot contain protected tags
 *
 * ERROR RE-EXPORTS
 *   VmdErrorCode, createVmdError Re-exported from vmd_util for convenience
 *
 * USAGE
 * ----------------------------------------------------------------------------
 *
 * Used by MarkdownCompiler for pre-validation and line tracking:
 *
 *   scanVmdBlocks(source, frontmatterOffset);
 *   detectNestedCodeBlocks(body, getLine, getLoc);
 *   const location = getFileLocation();
 *
 * ============================================================================
 */

import { VmdErrorCode, createVmdError, ErrorLocation } from './vmd_util';

// Re-export error utilities for extensions
export { VmdErrorCode, createVmdError } from './vmd_util';

// ============================================================================
// Line Tracker - for accurate line number reporting
// ============================================================================

// Full source storage
let fullSource: string = '';
let frontmatterOffset: number = 0;

// Array to store line numbers in order of appearance
let postBlockLines: number[] = [];
let currentIndex: number = 0;

/**
 * Clear tracker for a new file
 */
export function clearLineTracker(filePath?: string): void {
  fullSource = '';
  frontmatterOffset = 0;
  postBlockLines = [];
  currentIndex = 0;
}

/**
 * Pre-scan markdown to record all VMD block positions
 * This must be called BEFORE marked processes the markdown
 */
export function scanVmdBlocks(source: string, offset: number = 0): void {
  fullSource = source;
  frontmatterOffset = offset;
  postBlockLines = [];
  currentIndex = 0;

  // Find all <post> blocks and record their line numbers
  const regex = /<post>[\s\S]*?<\/post>/g;
  let match;

  while ((match = regex.exec(source)) !== null) {
    const startPos = match.index;

    // Calculate line number
    const textBefore = source.substring(0, startPos);
    const lineNumber = (textBefore.match(/\n/g) || []).length + 1 + offset;

    // Store line number in array
    postBlockLines.push(lineNumber);
  }
}

/**
 * Get the line number for the next post block in sequence.
 * This uses an internal index that increments with each call.
 * Must be called in the same order as scanVmdBlocks found the blocks.
 */
export function getBlockLineNumber(): number | undefined {
  if (currentIndex < postBlockLines.length) {
    const line = postBlockLines[currentIndex];
    currentIndex++;
    return line;
  }
  return undefined;
}

/**
 * Reset the block index counter.
 * Call this before tokenization starts to ensure line numbers
 * are returned from the beginning.
 */
export function resetBlockIndices(): void {
  currentIndex = 0;
}

/**
 * Calculate line number for content within a block
 * @param blockStartLine - The starting line of the block
 * @param content - The full block content
 * @param subContentOffset - The offset of subContent within content
 */
export function calculateSubContentLine(
  blockStartLine: number,
  content: string,
  subContentOffset: number
): number {
  const textBefore = content.substring(0, subContentOffset);
  const linesBefore = (textBefore.match(/\n/g) || []).length;
  return blockStartLine + linesBefore;
}

/**
 * Debug: Print all tracked positions
 */
export function debugPrintTrackedBlocks(): void {
  console.log('=== Tracked VMD Blocks ===');
  postBlockLines.forEach((line, idx) => {
    console.log(`  [${idx}] Line ${line}`);
  });
  console.log(`Current index: ${currentIndex}`);
  console.log('==========================');
}

// ============================================================================
// Validation Helpers
// ============================================================================

// Tags that are protected and cannot be nested inside other custom blocks
export const PROTECTED_TAGS = ['post', 'lft', 'rt'];

// Tags that can only appear inside <post>
export const POST_ONLY_TAGS = ['lft', 'rt'];

// Container tags that cannot contain protected tags
export const CONTAINER_TAGS = ['info', 'warning', 'success', 'smallimg'];

/**
 * Code region detector
 * Returns true if the given position is inside any code context:
 * - Fenced code block (```...```)
 * - Inline code (`...`)
 */
export function isPositionInCode(source: string, position: number): boolean {
  // First, identify all fenced code block regions
  const fencedBlocks: Array<[number, number]> = [];
  const lines = source.split('\n');
  let charPos = 0;
  let fencedStart: number | null = null;

  for (const line of lines) {
    const trimmedLine = line.trim();
    if (/^```+/.test(trimmedLine)) {
      if (fencedStart === null) {
        fencedStart = charPos;
      } else {
        fencedBlocks.push([fencedStart, charPos + line.length + 1]); // +1 for newline
        fencedStart = null;
      }
    }
    charPos += line.length + 1; // +1 for newline
  }

  // Check if position is in a fenced block
  for (const [start, end] of fencedBlocks) {
    if (position >= start && position < end) {
      return true;
    }
  }

  // If not in fenced block, check for inline code
  // Find all inline code regions (not inside fenced blocks)
  const inlineCodeRegex = /`[^`]*`/g;
  let match;
  while ((match = inlineCodeRegex.exec(source)) !== null) {
    // Skip if this inline code is inside a fenced block
    let inFenced = false;
    for (const [start, end] of fencedBlocks) {
      if (match.index >= start && match.index < end) {
        inFenced = true;
        break;
      }
    }
    if (!inFenced) {
      const matchStart = match.index;
      const matchEnd = match.index + match[0].length;
      if (position > matchStart && position < matchEnd) {
        return true;
      }
    }
  }

  return false;
}

/**
 * Calculate line number by counting newlines in text before a position
 * Returns the actual line number in the full markdown file (including frontmatter)
 */
export function getLineAtPosition(fullSource: string, position: number, filePath?: string): number {
  const textBefore = fullSource.substring(0, position);
  const bodyLineNumber = (textBefore.match(/\n/g) || []).length + 1;

  // Add frontmatter offset to get the actual line number
  if (filePath) {
    const offset = getFrontmatterLineCount(filePath);
    return bodyLineNumber + offset;
  }
  return bodyLineNumber;
}

// Compilation context storage
const fileSourceContext: Map<string, string> = new Map();
const fileFrontmatterLineCount: Map<string, number> = new Map();

/**
 * Store compilation context for a file
 */
export function setCompilationContext(
  filePath: string,
  markdownSource: string,
  frontmatterLineCount: number = 0
): void {
  fileSourceContext.set(filePath, markdownSource);
  fileFrontmatterLineCount.set(filePath, frontmatterLineCount);
}

/**
 * Clear compilation context for a file
 */
export function clearCompilationContext(filePath: string): void {
  fileSourceContext.delete(filePath);
  fileFrontmatterLineCount.delete(filePath);
}

/**
 * Get the full markdown source for a file
 */
export function getMarkdownSource(filePath: string): string | undefined {
  return fileSourceContext.get(filePath);
}

/**
 * Get the frontmatter line count for a file
 */
export function getFrontmatterLineCount(filePath: string): number {
  return fileFrontmatterLineCount.get(filePath) || 0;
}

/**
 * Check if compilation context exists for a file
 */
export function hasCompilationContext(filePath: string): boolean {
  return fileSourceContext.has(filePath);
}

/**
 * Check if content contains protected tags that would be invalid nesting
 */
export function checkInvalidNesting(content: string, parentTag: string): { tag: string; line: number } | null {
  const lines = content.split('\n');
  let inCodeBlock = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmedLine = line.trim();

    // Check for code block boundaries
    const codeBlockMatch = line.match(/^(```+)(\w*)/);
    if (codeBlockMatch) {
      const ticks = codeBlockMatch[1].length;
      if (ticks >= 3) {
        inCodeBlock = !inCodeBlock;
        continue;
      }
    }

    // Skip content inside code blocks
    if (inCodeBlock) {
      continue;
    }

    // Check for opening of protected tags
    for (const tag of PROTECTED_TAGS) {
      const openRegex = new RegExp(`^\\s*<${tag}\\b[^>]*>`, 'i');
      if (openRegex.test(trimmedLine)) {
        // Check if parent is a container tag (which cannot contain protected tags)
        if (CONTAINER_TAGS.includes(parentTag.toLowerCase())) {
          return { tag, line: i + 1 };
        }

        // Check if it's lft or rt outside of post
        if (POST_ONLY_TAGS.includes(tag) && parentTag.toLowerCase() !== 'post') {
          return { tag, line: i + 1 };
        }
      }
    }
  }

  return null;
}

/**
 * Check if content contains single backtick at line start (invalid for VMD)
 */
export function checkSingleBacktickInContent(content: string): number | null {
  const lines = content.split('\n');
  let inCodeBlock = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmedLine = line.trim();

    // Check for code block boundaries
    const codeBlockMatch = line.match(/^(```+)(\w*)/);
    if (codeBlockMatch) {
      const ticks = codeBlockMatch[1].length;
      if (ticks >= 3) {
        inCodeBlock = !inCodeBlock;
        continue;
      }
    }

    // Skip content inside code blocks
    if (inCodeBlock) {
      continue;
    }

    // Check for single backtick at start of line followed by content
    if (/^`[^\s`]/.test(trimmedLine)) {
      return i + 1;
    }
  }

  return null;
}

/**
 * Get file location from lexer context
 */
export function getFileLocation(context: any): { file?: string; line?: number; column?: number } {
  const location: { file?: string; line?: number; column?: number } = {};
  if (context && context.lexer) {
    if (context.lexer.filePath) {
      location.file = context.lexer.filePath;
    }
  }
  return location;
}

/**
 * Find position of a substring within full source, starting from a given offset
 */
export function findPosition(fullSource: string, searchText: string, startOffset: number = 0): number {
  return fullSource.indexOf(searchText, startOffset);
}

// ============================================================================
// Syntax Validators
// ============================================================================


/**
 * Detect nested code blocks (code blocks inside code blocks)
 */
export function detectNestedCodeBlocks(
  body: string,
  getActualLineNumber: (line: number) => number,
  getLocation: () => ErrorLocation
): void {
  const lines = body.split('\n');
  let inCodeBlock = false;
  let codeBlockStartLine = 0;
  let backtickCount = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const codeFenceMatch = line.match(/^(```+)(\w*)/);

    if (codeFenceMatch) {
      const ticks = codeFenceMatch[1].length;

      if (!inCodeBlock) {
        inCodeBlock = true;
        codeBlockStartLine = i + 1;
        backtickCount = ticks;
      } else if (ticks === backtickCount) {
        inCodeBlock = false;
        backtickCount = 0;
      } else if (ticks >= 3) {
        const actualLine = getActualLineNumber(i + 1);
        throw createVmdError(
          VmdErrorCode.MARKDOWN_NESTED_CODE_BLOCK,
          { line: actualLine, expected: backtickCount, found: ticks },
          { ...getLocation(), line: actualLine }
        );
      }
    }
  }
}

/**
 * Detect single backtick code blocks inside custom markup blocks
 * Only triple backticks (```) are allowed for code blocks in VMD
 */
export function detectSingleBacktickCodeBlocks(
  body: string,
  getActualLineNumber: (line: number) => number,
  getLocation: () => ErrorLocation
): void {
  const lines = body.split('\n');
  let inCodeBlock = false;

  // Track the hierarchy of custom blocks
  const blockStack: Array<{ tag: string; line: number }> = [];

  // Custom block tags that trigger validation
  const customBlockTags = ['post', 'lft', 'rt', 'info', 'warning', 'success', 'smallimg'];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmedLine = line.trim();

    // Check for code block boundaries (triple backticks)
    const codeBlockMatch = line.match(/^(```+)(\w*)/);
    if (codeBlockMatch) {
      const ticks = codeBlockMatch[1].length;
      if (ticks >= 3) {
        inCodeBlock = !inCodeBlock;
        continue;
      }
    }

    // Skip content inside code blocks
    if (inCodeBlock) {
      continue;
    }

    // Track custom block hierarchy
    for (const tag of customBlockTags) {
      const openRegex = new RegExp(`^\\s*<${tag}\\b[^>]*>`, 'i');
      const closeRegex = new RegExp(`^\\s*</${tag}>`, 'i');

      if (openRegex.test(trimmedLine)) {
        blockStack.push({ tag: tag.toLowerCase(), line: i + 1 });
      }

      if (closeRegex.test(trimmedLine)) {
        for (let j = blockStack.length - 1; j >= 0; j--) {
          if (blockStack[j].tag === tag.toLowerCase()) {
            blockStack.splice(j, blockStack.length - j);
            break;
          }
        }
      }
    }

    // Check for single backtick used as code block delimiter inside custom blocks
    if (blockStack.length > 0 && /^`[^\s`]/.test(trimmedLine)) {
      const actualLine = getActualLineNumber(i + 1);
      throw createVmdError(
        VmdErrorCode.MARKDOWN_SINGLE_BACKTICK_CODEBLOCK,
        { line: actualLine },
        { ...getLocation(), line: actualLine }
      );
    }
  }
}

/**
 * Detect invalid tag nesting: <post>, <lft>, <rt> cannot be nested inside other custom blocks
 */
export function detectInvalidTagNesting(
  body: string,
  getActualLineNumber: (line: number) => number,
  getLocation: () => ErrorLocation
): void {
  const lines = body.split('\n');
  let inCodeBlock = false;

  // Track the hierarchy of custom blocks
  const blockStack: Array<{ tag: string; line: number }> = [];

  // Tags that cannot contain <post>, <lft>, or <rt>
  const containerTags = ['info', 'warning', 'success', 'smallimg'];
  // Tags that are protected (cannot be nested inside other custom blocks except post)
  const protectedTags = ['post', 'lft', 'rt'];
  // Tags that can only be inside <post>
  const postOnlyTags = ['lft', 'rt'];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmedLine = line.trim();

    // Check for code block boundaries
    const codeBlockMatch = line.match(/^(```+)(\w*)/);
    if (codeBlockMatch) {
      const ticks = codeBlockMatch[1].length;
      if (ticks >= 3) {
        inCodeBlock = !inCodeBlock;
        continue;
      }
    }

    // Skip content inside code blocks
    if (inCodeBlock) {
      continue;
    }

    // Check for opening tags
    const openTagMatch = trimmedLine.match(/^<([a-zA-Z][a-zA-Z0-9]*)\b[^>]*>/);

    if (openTagMatch) {
      const tagName = openTagMatch[1].toLowerCase();

      // Check if this is a protected tag being nested inside a container
      if (protectedTags.includes(tagName)) {
        for (const block of blockStack) {
          if (containerTags.includes(block.tag)) {
            const actualLine = getActualLineNumber(i + 1);
            throw createVmdError(
              VmdErrorCode.MARKDOWN_INVALID_TAG_NESTING,
              {
                outerTag: block.tag,
                innerTag: tagName,
                line: actualLine
              },
              { ...getLocation(), line: actualLine }
            );
          }
        }

        // lft and rt can only be inside post
        if (postOnlyTags.includes(tagName)) {
          const isInsidePost = blockStack.some(b => b.tag === 'post');
          if (!isInsidePost) {
            const actualLine = getActualLineNumber(i + 1);
            throw createVmdError(
              VmdErrorCode.MARKDOWN_INVALID_TAG_NESTING,
              {
                outerTag: 'none (root level)',
                innerTag: tagName,
                line: actualLine
              },
              { ...getLocation(), line: actualLine }
            );
          }
        }
      }

      // Check if this is a self-closing tag
      const closeTagPattern = new RegExp(`<\\/${tagName}>`, 'i');
      const isSelfClosing = trimmedLine.includes('/>') || closeTagPattern.test(trimmedLine);

      if (!isSelfClosing) {
        blockStack.push({ tag: tagName, line: i + 1 });
      }
    }

    // Check for closing tags
    const closeTagMatch = trimmedLine.match(/^<\/([a-zA-Z][a-zA-Z0-9]*)>/);
    if (closeTagMatch) {
      const tagName = closeTagMatch[1].toLowerCase();
      while (blockStack.length > 0) {
        const popped = blockStack.pop();
        if (popped && popped.tag === tagName) {
          break;
        }
      }
    }
  }
}

/**
 * Detect empty markup elements
 */
export function detectEmptyMarkup(html: string): void {
  const emptyPatterns = [
    { tag: 'bold', pattern: /<bold>\s*<\/bold>/g },
    { tag: 'italic', pattern: /<italic>\s*<\/italic>/g },
    { tag: 'strike', pattern: /<strike>\s*<\/strike>/g },
    { tag: 'inlinecode', pattern: /<inlinecode>\s*<\/inlinecode>/g },
    { tag: 'boldit', pattern: /<boldit>\s*<\/boldit>/g },
  ];

  for (const { tag, pattern } of emptyPatterns) {
    const matches = html.match(pattern);
    if (matches && matches.length > 0) {
      console.warn(
        `[WARNING] Empty ${tag} element detected (${matches.length} occurrence${matches.length > 1 ? 's' : ''})`
      );
    }
  }
}
