/**
 * ============================================================================
 * types.ts - VMD Core Type Definitions, generated by kimi-k2.5
 * ============================================================================
 *
 * This module defines the TypeScript interfaces and types used throughout
 * the VMD (v0plex Markdown) system. These types represent the data structures
 * for parsed content, site navigation, and compilation results.
 *
 * MODULE COMPOSITION
 * ----------------------------------------------------------------------------
 *
 * FrontMatterAttributes ...... Interface for YAML frontmatter metadata from
 *                              markdown files. Includes standard fields like
 *                              title, dates, author, plus extensible key-value
 *                              pairs for custom metadata.
 *
 * ParseResult ................ Bundles the output of frontmatter parsing:
 *                              extracted attributes, remaining body content,
 *                              and line count consumed by frontmatter.
 *
 * ImageReference ............. Simple pair mapping original image filename
 *                              to its hashed counterpart for tracking usage.
 *
 * NavigationNode ............. Recursive tree structure representing the
 *                              site navigation hierarchy. Supports sections,
 *                              folders, and pages with full metadata including
 *                              paths, hashes, custom TSX flags, associated
 *                              code files and images, tags, locale codes, and
 *                              cross-language linking for i18n.
 *
 * SiteData ................... Aggregated site-wide metadata including the
 *                              complete navigation tree, all processed images,
 *                              available language codes, and default locale.
 *
 * ProcessedMarkdown .......... Output structure from markdown compilation
 *                              containing transformed HTML, list of generated
 *                              code files, and references to used images.
 *
 * USAGE
 * ----------------------------------------------------------------------------
 *
 * These types are imported across the VMD system for type safety:
 *
 *   import { FrontMatterAttributes, NavigationNode } from './types';
 *
 * ============================================================================
 */

export interface FrontMatterAttributes {
  title?: string;
  created_at?: string;
  last_updated_at?: string;
  author?: string;
  has_custom_tsx?: boolean | string;
  [key: string]: any;
}

export interface ParseResult {
  attributes: FrontMatterAttributes;
  body: string;
  frontmatterLineCount: number;
}

export interface ImageReference {
  originalName: string;
  hashName: string;
}

export interface NavigationNode {
  title: string;
  type: 'page' | 'folder';
  path: string; // The web path /hash
  hash: string;
  hasCustomTsx: boolean;
  mdPath: string; // Relative path to source
  tsxPath: string; // Relative path to generated TSX
  codeFiles: { originalPath: string; hashPath: string }[];
  images: { originalName: string; hashPath: string }[];
  tags: string[]; // Tags from frontmatter
  locale?: string; // Language code (zh, en, fr, etc.) - optional for backward compatibility
  children: NavigationNode[];
  // Cross-language links: locale -> path mapping for same content in different languages
  // Only populated for 'page' type nodes
  languageLinks?: Record<string, string>;
  // Prefix identifier for matching pages across languages (e.g., "01_", "02_01_")
  prefixId?: string;
}

export interface SiteData {
  navigation: NavigationNode[];
  images: { originalPath: string; hashPath: string }[];
  availableLocales?: string[]; // List of available language codes
  defaultLocale?: string; // Default language code
}

export interface ProcessedMarkdown {
  html: string;
  generatedFiles: string[];
  usedImages: ImageReference[];
}
