/**
 * ============================================================================
 * vmd_util.ts - VMD Utility Core File, generated by kimi-k2.5
 * ============================================================================
 *
 * This is the central orchestration module of the VMD (v0plex Markdown) parsing
 * system. It consolidates functionality previously scattered across multiple
 * files into a cohesive utility library that handles the entire pipeline from
 * raw markdown files to compiled React components and site navigation.
 *
 * THE BIG PICTURE
 * ----------------------------------------------------------------------------
 *
 * VmdUtil operates in two primary modes:
 *
 *   LOCAL MODE  - Uses markdown files from the local `dev/` directory
 *   REMOTE MODE - Clones a Git repository, builds from remote content
 *
 * The build pipeline flows through these stages:
 *
 *   1. PREPARE  - Validate config, clone repo (remote), clean output dirs
 *   2. PARSE    - Scan directory structure, parse frontmatter from markdown
 *   3. RESOLVE  - Resolve @git placeholders for dates/authors via git history
 *   4. PROCESS  - Hash and copy images, extract code blocks to files
 *   5. COMPILE  - Transform markdown to React TSX components
 *   6. LINK     - Build cross-language navigation links
 *   7. OUTPUT   - Write page.tsx files and site navigation JSON
 *
 * MODULE COMPOSITION
 * ----------------------------------------------------------------------------
 *
 * ERROR SYSTEM (exported types & functions)
 *   The error system provides structured, code-based error reporting with
 *   precise location tracking (file, line, column). Error codes follow a
 *   systematic naming convention: E-prefix for general errors (E1xxx system,
 *   E2xxx frontmatter, E3xxx markdown) and V-prefix for v0plex-specific
 *   errors (V0xxx config, V1xxx git, V2xxx dev folder). The VmdError class
 *   extends native Error with formatting methods for CLI output and JSON
 *   serialization. Helper functions createVmdError, isVmdError, and wrapError
 *   provide convenient error construction and type checking.
 *
 * TYPE DEFINITIONS (exported interfaces)
 *   Core data structures define the shape of parsed content and site metadata.
 *   FrontMatterAttributes captures YAML key-value pairs from markdown headers.
 *   ParseResult bundles parsed attributes with the remaining body content.
 *   NavigationNode represents the site tree structure supporting sections,
 *   folders, and pages with localization. SiteData aggregates the complete
 *   site state for frontend consumption including navigation, images, and
 *   available locales.
 *
 * VmdUtil CLASS
 *   The main utility class encapsulating all build operations. State includes
 *   the project root path, accumulated errors, image name-to-hash mappings,
 *   site-wide image registry, generated TSX tracking, navigation tree, and
 *   remote/local mode flag.
 *
 *   Error Management: createError generates VmdError instances and optionally
 *   accumulates them; getErrorStatus reports error counts with print/clear
 *   options for CLI feedback.
 *
 *   Filesystem Operations: fileOperation provides unified read/write/directory
 *   creation with automatic error handling; cleanBuildOutput purges previous
 *   build artifacts from vmdcode, vmdimage, vmdjson, and page output
 *   directories; resetDirectory clears contents while preserving the directory
 *   node; scanDirectoryForImages discovers image assets recursively.
 *
 *   Asset Processing: processImage hashes image content with SHA256 and copies
 *   to the vmdimage output directory with unique randomized filenames;
 *   validateImageExists ensures local image availability rejecting remote URLs;
 *   writeCodeFile persists code block content to vmdcode directory keyed by
 *   content hash; processImageAndGetHash locates and processes images by
 *   original path; getHashedImageName, hasImage, getAssetData, and resetAssets
 *   manage the image registry state.
 *
 *   Git Operations: checkGitAvailable tests git CLI availability; resolveDate
 *   converts @git placeholders to earliest or latest commit dates from history;
 *   resolveAuthor substitutes @git with git config user name and email;
 *   scanForGitPlaceholders scans content to determine if git resolution is
 *   required.
 *
 *   Frontmatter Parsing: parseFrontmatter extracts YAML metadata enclosed in
 *   --- delimiters; validateFrontmatter enforces required fields (title,
 *   created_at, last_updated_at, author, has_custom_tsx, tags) and format
 *   constraints; parseTags converts bracketed tag strings to arrays;
 *   hasCustomTsx checks for custom TSX flag; validateAuthorFormat validates
 *   author string syntax supporting names, emails, URLs, and @git placeholders.
 *
 *   Text & Hash Utilities: calculateHash provides SHA256 for content hashing
 *   and shake256 for compact path hashing; cleanTitle strips numeric prefixes
 *   and suffixes from filenames for display; formatText offers HTML escaping
 *   and capitalization transforms.
 *
 *   Site Building: build orchestrates the entire compilation process from
 *   input path to output site; validateAndScanDirectory ensures language
 *   folder validity and discovers images; traverseDirectory recursively builds
 *   the navigation tree respecting numeric ordering prefixes; processFile
 *   dispatches markdown or TSX handling by extension; processMarkdownFile
 *   parses frontmatter, resolves @git values, compiles markdown to React TSX,
 *   and writes page output; processTsxFile handles custom TSX components;
 *   generatePageComponent assembles the final React component with VMD
 *   component imports, theme provider, dates, and edit links;
 *   buildCrossLanguageLinks matches pages across language variants by numeric
 *   prefix; writeSiteData persists the complete navigation structure as JSON.
 *
 *   Git Sync Operations: getGitConfig retrieves repository settings;
 *   validateGitConfig enforces remote mode requirements; syncFromGit clones
 *   the configured repository and validates structure; validateRemoteDevStructure
 *   enforces strict dev/{language}/ layout for remote content;
 *   validateDevFolderStructure and validateDevFolder validate local content
 *   organization; checkForFilesRecursive determines directory content presence;
 *   run provides the CLI entry point coordinating sync, clean, and build phases.
 *
 * USAGE
 * ----------------------------------------------------------------------------
 *
 *   const util = new VmdUtil(projectRoot);
 *   const success = util.run(); // Full pipeline execution
 *
 * The VmdUtil class is designed to be instantiated per build session. Internal
 * state (errors, image maps, navigation) is reset between builds via instance
 * recreation rather than method calls.
 *
 * ============================================================================
 */

import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { execSync } from 'child_process';
import {
  BUILD_CONFIG,
  SITE_CONFIG,
  AVAILABLE_LANGUAGES,
  AVAILABLE_LANGUAGES_SUPPORT,
  DEFAULT_LOCALE,
  CONTENT_SOURCE_CONFIG,
  SITE_TITLE_BASE,
} from '../config/site.config';

// ============================================================================
// ERROR SYSTEM
// ============================================================================
//
// Provides standardized error handling for the VMD parsing system:
//
// - VmdErrorCode: Enum of all error codes with systematic naming
//   - E prefix: General errors (E1xxx system, E2xxx frontmatter, E3xxx markdown, etc.)
//   - V prefix: v0plex-specific errors (V0xxx config, V1xxx git, V2xxx dev folder)
//
// - ErrorLocation: Tracks file path, line, and column where errors occurred
//
// - ErrorMessages: Maps error codes to human-readable message generators
//
// - VmdError: Extended Error class with code, location, timestamp, and formatting
//
// - Helper functions: createVmdError, isVmdError, wrapError for convenient usage
//
// ============================================================================

export interface ErrorLocation {
  file?: string;
  line?: number;
  column?: number;
}

export enum VmdErrorCode {
  // System-level errors (E1xxx) - lowest level errors
  UNKNOWN_ERROR = 'E1000',
  CONFIG_ERROR = 'E1001',
  FILE_SYSTEM_ERROR = 'E1002',


  // Configuration errors (V0xxx) - site configuration related
  CONFIG_PARSE_ERROR = 'V0001',
  CONFIG_MISSING_REPO_URL = 'V0002',
  CONFIG_INVALID_BRANCH_NAME = 'V0003',

  // Git operation errors (V1xxx)
  GIT_CLONE_FAILED = 'V1000',
  GIT_CHECKOUT_FAILED = 'V1001',
  GIT_DELETE_FAILED = 'V1002',
  GIT_NOT_AVAILABLE = 'V1003',

  // dev folder errors (V2xxx)
  DEV_FOLDER_NOT_FOUND = 'V2000',
  DEV_FOLDER_NO_LANGUAGE = 'V2001',
  DEV_FOLDER_NO_FILES = 'V2002',
  DEV_FOLDER_INVALID_STRUCTURE = 'V2003',
  DEV_FOLDER_MISSING_REQUIRED_LANGUAGE = 'V2004',
  DEV_FOLDER_EXTRA_LANGUAGE = 'V2005',

  // Language configuration errors (V3xxx)
  LANGUAGE_NOT_ENABLED = 'V3000',

  // Frontmatter errors (E2xxx) - metadata at the head of Markdown files
  FRONTMATTER_PARSE_ERROR = 'E2000',
  FRONTMATTER_MISSING_REQUIRED = 'E2001',
  FRONTMATTER_INVALID_VALUE = 'E2002',
  FRONTMATTER_INVALID_FORMAT = 'E2003',
  FRONTMATTER_INVALID_AUTHOR_FORMAT = 'E2004',

  // Markdown compilation errors (E3xxx)
  MARKDOWN_COMPILE_ERROR = 'E3000',
  MARKDOWN_SYNTAX_ERROR = 'E3001',
  MARKDOWN_NESTED_CODE_BLOCK = 'E3002',
  MARKDOWN_XSS_DETECTED = 'E3003',
  MARKDOWN_EMPTY_MARKUP = 'E3004',
  MARKDOWN_SINGLE_BACKTICK_CODEBLOCK = 'E3005',
  MARKDOWN_INVALID_TAG_NESTING = 'E3006',

  // Extension syntax errors (E4xxx) - VMD-specific extensions
  EXTENSION_POST_MISSING_TAGS = 'E4000',
  EXTENSION_POST_INVALID_CONTENT = 'E4001',
  EXTENSION_POST_MISSING_IMAGE = 'E4002',
  EXTENSION_POST_MISSING_ALT = 'E4003',
  EXTENSION_CUSTOM_BLOCK_ERROR = 'E4004',
  EXTENSION_POST_INVALID_FORMAT = 'E4005',
  EXTENSION_POST_LFT_INVALID_TAG = 'E4006',
  EXTENSION_POST_LFT_INVALID_SPACING = 'E4007',
  EXTENSION_POST_LFT_CODE_BLOCK = 'E4008',
  EXTENSION_POST_LFT_DISALLOWED_TAG = 'E4009',
  EXTENSION_POST_LFT_BLOCK_MATH = 'E4010',
  EXTENSION_POST_LFT_IMAGE = 'E4011',
  EXTENSION_POST_LFT_BLOCKQUOTE = 'E4012',
  EXTENSION_POST_LFT_INVALID_SPACING_DUPLICATE = 'E4013',
  EXTENSION_EMPTY_CUSTOM_BLOCK = 'E4014',

  // Table errors (E41xx) - tables cannot contain certain block elements
  TABLE_INVALID_CONTENT = 'E4100',
  TABLE_DISALLOWED_BLOCK_ELEMENT = 'E4101',
  TABLE_DISALLOWED_IMAGE = 'E4102',
  TABLE_DISALLOWED_LIST = 'E4103',
  TABLE_DISALLOWED_BLOCKQUOTE = 'E4104',
  TABLE_DISALLOWED_CODE_BLOCK = 'E4105',
  TABLE_DISALLOWED_BLOCK_MATH = 'E4106',
  TABLE_INVALID_FORMAT = 'E4107',

  // Asset processing errors (E5xxx)
  ASSET_PROCESS_ERROR = 'E5000',
  IMAGE_NOT_FOUND = 'E5001',
  IMAGE_PROCESS_FAILED = 'E5002',
  CODE_FILE_WRITE_ERROR = 'E5003',

  // Build errors (E6xxx)
  BUILD_ERROR = 'E6000',
  BUILD_MISSING_H1 = 'E6001',
  BUILD_MISSING_CUSTOM_TSX = 'E6002',
  BUILD_INVALID_PATH = 'E6003',
  BUILD_GIT_NOT_AVAILABLE = 'E6004',
  BUILD_INVALID_LANGUAGE_FOLDER = 'E6005',
  BUILD_I18N_PREFIX_MISMATCH = 'E6006',

  // Filesystem operation errors (E7xxx)
  FS_CLEAN_FAILED = 'E7000',
  FS_DELETE_FILE_FAILED = 'E7001',
  FS_CREATE_DIR_FAILED = 'E7002',
  FS_RESET_DIR_FAILED = 'E7003',
  FS_READ_FILE_FAILED = 'E7004',
  FS_WRITE_FILE_FAILED = 'E7005',
  FS_WRITE_SITE_DATA_FAILED = 'E7006',

  // Author format errors (E8xxx)
  AUTHOR_LIST_EMPTY = 'E8000',
  AUTHOR_MULTIPLE_GIT_PLACEHOLDER = 'E8001',
  AUTHOR_INVALID_ENTRY_FORMAT = 'E8002',
  AUTHOR_NAME_EMPTY = 'E8003',
  AUTHOR_DUPLICATE_EMAIL = 'E8004',
  AUTHOR_DUPLICATE_URL = 'E8005',
  AUTHOR_INVALID_EMAIL_OR_URL = 'E8006',
  AUTHOR_EMPTY_ENTRY = 'E8007',
}

export const ErrorMessages: Record<VmdErrorCode, (details?: Record<string, any>) => string> = {
  // System errors
  [VmdErrorCode.UNKNOWN_ERROR]: (d) => `Unknown error${d?.details ? `: ${d.details}` : ''}`,
  [VmdErrorCode.CONFIG_ERROR]: (d) => `Configuration error: ${d?.message || 'Invalid configuration'}`,
  [VmdErrorCode.FILE_SYSTEM_ERROR]: (d) => `Filesystem error: ${d?.message || 'Unable to access file'}`,


  // Configuration errors
  [VmdErrorCode.CONFIG_PARSE_ERROR]: (d) => `Failed to parse configuration: ${d?.message || 'Unknown error'}`,
  [VmdErrorCode.CONFIG_MISSING_REPO_URL]: (d) => `REPO_URL is required when USE_LOCAL_MARKDOWN is false. Please specify the git repository URL in config/site.config.ts`,
  [VmdErrorCode.CONFIG_INVALID_BRANCH_NAME]: (d) => `Branch name "${d?.branch}" contains invalid characters. Branch names can only contain letters, numbers, hyphens, underscores, dots, and slashes.`,

  // Git operation errors
  [VmdErrorCode.GIT_CLONE_FAILED]: (d) => `Failed to clone repository from ${d?.repoUrl || 'unknown address'}`,
  [VmdErrorCode.GIT_CHECKOUT_FAILED]: (d) => `Failed to checkout commit ${d?.commitHash || 'unknown'}`,
  [VmdErrorCode.GIT_DELETE_FAILED]: (d) => `Failed to delete dev folder: ${d?.message || 'Unknown error'}`,
  [VmdErrorCode.GIT_NOT_AVAILABLE]: (d) => `Git is not available. Please ensure Git is installed and added to your system PATH.`,

  // dev folder errors
  [VmdErrorCode.DEV_FOLDER_NOT_FOUND]: (d) => `dev folder does not exist`,
  [VmdErrorCode.DEV_FOLDER_NO_LANGUAGE]: (d) => `dev folder must contain at least one language folder (e.g., "en", "zh")`,
  [VmdErrorCode.DEV_FOLDER_NO_FILES]: (d) => `dev folder must contain at least one file (cannot be folders only)`,
  [VmdErrorCode.DEV_FOLDER_INVALID_STRUCTURE]: (d) => `Invalid dev folder structure. Remote mode requires: dev/{language}/... format where language must be one of the configured valid languages`,
  [VmdErrorCode.DEV_FOLDER_MISSING_REQUIRED_LANGUAGE]: (d) => `Missing required language folder(s): ${d?.missing?.join(', ')}. Configuration requires: ${d?.required?.join(', ')}`,
  [VmdErrorCode.DEV_FOLDER_EXTRA_LANGUAGE]: (d) => `Found unconfigured language folder(s): ${d?.extra?.join(', ')}. Allowed languages: ${d?.allowed?.join(', ')}`,

  // Language configuration errors
  [VmdErrorCode.LANGUAGE_NOT_ENABLED]: (d) => `Language '${d?.language}' is not enabled. Enabled languages: ${d?.enabled?.join(', ')}. Add it to ENABLED_LANGUAGES in config/site.config.ts to enable.`,

  // Frontmatter errors
  [VmdErrorCode.FRONTMATTER_PARSE_ERROR]: (d) => `Failed to parse frontmatter`,
  [VmdErrorCode.FRONTMATTER_MISSING_REQUIRED]: (d) => `Missing required frontmatter attribute(s): ${d?.fields?.join(', ') || 'unknown fields'}`,
  [VmdErrorCode.FRONTMATTER_INVALID_VALUE]: (d) => `Invalid value for frontmatter attribute '${d?.field}': ${d?.value}`,
  [VmdErrorCode.FRONTMATTER_INVALID_FORMAT]: (d) => `Invalid frontmatter format: ${d?.message}`,
  [VmdErrorCode.FRONTMATTER_INVALID_AUTHOR_FORMAT]: (d) => `Invalid author format: ${d?.message}. Expected format: "Name1 | Name2 | Name->email@example.com"`,

  // Markdown compilation errors
  [VmdErrorCode.MARKDOWN_COMPILE_ERROR]: (d) => `Markdown compilation failed${d?.details ? `: ${d.details}` : ''}`,
  [VmdErrorCode.MARKDOWN_SYNTAX_ERROR]: (d) => `Markdown syntax error${d?.details ? `: ${d.details}` : ''}`,
  [VmdErrorCode.MARKDOWN_NESTED_CODE_BLOCK]: (d) => `Nested code block detected at line ${d?.line}. Code blocks cannot be nested inside other code blocks.`,
  [VmdErrorCode.MARKDOWN_XSS_DETECTED]: (d) => `XSS attack pattern '${d?.pattern}' detected in math formula: ${d?.formula || ''}`,
  [VmdErrorCode.MARKDOWN_EMPTY_MARKUP]: (d) => `Empty ${d?.type} element(s) detected (${d?.count || 1} occurrence(s))`,
  [VmdErrorCode.MARKDOWN_SINGLE_BACKTICK_CODEBLOCK]: (d) => `Single backtick code blocks are not allowed in VMD compiler. At line ${d?.line || 'unknown'}, please use triple backticks (\`\`\`) for code blocks.`,
  [VmdErrorCode.MARKDOWN_INVALID_TAG_NESTING]: (d) => `Invalid tag nesting: <${d?.outerTag}> cannot contain <${d?.innerTag}>, location: line ${d?.line || 'unknown'}`,

  // Extension syntax errors
  [VmdErrorCode.EXTENSION_POST_MISSING_TAGS]: (d) => `Post block must contain both <lft> and <rt> tags`,
  [VmdErrorCode.EXTENSION_POST_INVALID_CONTENT]: (d) => {
    if (d?.type === 'text_not_allowed') return `Post <rt> can only contain images, no other text is allowed`;
    if (d?.type === 'missing_newline_between_images') return `Each image in Post <rt> must be on its own line`;
    if (d?.type === 'text_between_images') return `Post <rt> can only contain images, no text allowed between images`;
    if (d?.type === 'missing_alt') return `Image is missing alt text`;
    if (d?.type === 'text_after_image') return `Post <rt> can only contain images, text found on same line as image`;
    return `Post <rt> only allows images, found content: '${d?.content || 'unknown'}'`;
  },
  [VmdErrorCode.EXTENSION_POST_MISSING_IMAGE]: (d) => `Post <rt> must contain at least one image`,
  [VmdErrorCode.EXTENSION_POST_MISSING_ALT]: (d) => `Images in Post <rt> must have alt text`,
  [VmdErrorCode.EXTENSION_CUSTOM_BLOCK_ERROR]: (d) => `Custom block <${d?.blockName}> processing failed`,
  [VmdErrorCode.EXTENSION_POST_INVALID_FORMAT]: (d) => {
    if (d?.type === 'post_to_lft_spacing') return `Exactly one space or newline is required between <post> and <lft>`;
    if (d?.type === 'lft_to_rt_spacing') return `Exactly one space or newline is required between </lft> and <rt>`;
    if (d?.type === 'rt_to_post_spacing') return `Exactly one space or newline is required between </rt> and </post>`;
    return `Post block format error`;
  },
  [VmdErrorCode.EXTENSION_POST_LFT_INVALID_TAG]: (d) => `Post <lft> contains invalid HTML tag '${d?.tag}'. Only inline code, smallimg, and inline math are allowed`,
  [VmdErrorCode.EXTENSION_POST_LFT_INVALID_SPACING]: (d) => {
    if (d?.type === 'no_images') return `No images found in <rt> section`;
    if (d?.type === 'after_rt') return `Empty line required after <rt>`;
    if (d?.type === 'before_rt') return `Empty line required before </rt>`;
    return `Post <rt> image spacing error`;
  },
  [VmdErrorCode.EXTENSION_POST_LFT_CODE_BLOCK]: (d) => `Code blocks are not allowed inside <post> blocks${d?.line ? ` (at line ${d.line})` : ''}`,
  [VmdErrorCode.EXTENSION_POST_LFT_DISALLOWED_TAG]: (d) => `Tag <${d?.tag}> is not allowed inside <post> blocks${d?.line ? ` (at line ${d.line})` : ''}`,
  [VmdErrorCode.EXTENSION_POST_LFT_BLOCK_MATH]: (d) => `Block-level math is not allowed inside <post> blocks${d?.line ? ` (at line ${d.line})` : ''}`,
  [VmdErrorCode.EXTENSION_POST_LFT_IMAGE]: (d) => `Regular images are not allowed inside <lft>, please use <smallimg>${d?.line ? ` (at line ${d.line})` : ''}`,
  [VmdErrorCode.EXTENSION_POST_LFT_BLOCKQUOTE]: (d) => `Blockquotes are not allowed inside <post> blocks${d?.line ? ` (at line ${d.line})` : ''}`,
  [VmdErrorCode.EXTENSION_POST_LFT_INVALID_SPACING_DUPLICATE]: (d) => `Invalid Post block spacing`,
  [VmdErrorCode.EXTENSION_EMPTY_CUSTOM_BLOCK]: (d) => `Empty custom block detected`,

  // Table errors
  [VmdErrorCode.TABLE_INVALID_CONTENT]: (d) => `Invalid table content`,
  [VmdErrorCode.TABLE_DISALLOWED_BLOCK_ELEMENT]: (d) => `Block elements are not allowed inside tables`,
  [VmdErrorCode.TABLE_DISALLOWED_IMAGE]: (d) => `Images are not allowed inside tables`,
  [VmdErrorCode.TABLE_DISALLOWED_LIST]: (d) => `Lists are not allowed inside tables`,
  [VmdErrorCode.TABLE_DISALLOWED_BLOCKQUOTE]: (d) => `Blockquotes are not allowed inside tables`,
  [VmdErrorCode.TABLE_DISALLOWED_CODE_BLOCK]: (d) => `Code blocks are not allowed inside tables`,
  [VmdErrorCode.TABLE_DISALLOWED_BLOCK_MATH]: (d) => `Block-level math is not allowed inside tables`,
  [VmdErrorCode.TABLE_INVALID_FORMAT]: (d) => `Invalid table format`,

  // Asset processing errors
  [VmdErrorCode.ASSET_PROCESS_ERROR]: (d) => `Asset processing error: ${d?.message}`,
  [VmdErrorCode.IMAGE_NOT_FOUND]: (d) => `Image not found: "${d?.imageName || d?.imagePath}"${d?.searchedPaths ? '\n  Searched paths: ' + d.searchedPaths.join(', ') : ''}`,
  [VmdErrorCode.IMAGE_PROCESS_FAILED]: (d) => `Failed to process image "${d?.imagePath}": ${d?.details}`,
  [VmdErrorCode.CODE_FILE_WRITE_ERROR]: (d) => `Failed to write code file "${d?.filePath}": ${d?.details}`,

  // Build errors
  [VmdErrorCode.BUILD_ERROR]: (d) => `Build error: ${d?.details}`,
  [VmdErrorCode.BUILD_MISSING_H1]: (d) => `Markdown file must start with a level 1 heading (# Title)`,
  [VmdErrorCode.BUILD_MISSING_CUSTOM_TSX]: (d) => `Missing custom TSX file: "${d?.expectedPath}" (frontmatter has has_custom_tsx: true)`,
  [VmdErrorCode.BUILD_INVALID_PATH]: (d) => `Invalid build path: "${d?.path}"`,
  [VmdErrorCode.BUILD_GIT_NOT_AVAILABLE]: (d) => `Git is not available. Please install git or remove the @git placeholder from frontmatter.`,
  [VmdErrorCode.BUILD_INVALID_LANGUAGE_FOLDER]: (d) => `Invalid language folder found: "${d?.invalidFolders}". Valid folders: ${d?.validFolders}`,
  [VmdErrorCode.BUILD_I18N_PREFIX_MISMATCH]: (d) => `i18n prefix mismatch: "${d?.prefixPath}" exists in [${d?.pageLocales}] but missing [${d?.missingLocales}]. Configured languages: [${d?.configuredLocales}]`,

  // Filesystem operation errors
  [VmdErrorCode.FS_CLEAN_FAILED]: (d) => `Failed to clean directory: ${d?.error}`,
  [VmdErrorCode.FS_DELETE_FILE_FAILED]: (d) => `Failed to delete file "${d?.file}": ${d?.error}`,
  [VmdErrorCode.FS_CREATE_DIR_FAILED]: (d) => `Failed to create directory "${d?.dir}": ${d?.error}`,
  [VmdErrorCode.FS_RESET_DIR_FAILED]: (d) => `Failed to reset directory "${d?.dir}": ${d?.error}`,
  [VmdErrorCode.FS_READ_FILE_FAILED]: (d) => `Failed to read file: ${d?.error || 'Unknown error'}`,
  [VmdErrorCode.FS_WRITE_FILE_FAILED]: (d) => `Failed to write file: ${d?.error || 'Unknown error'}`,
  [VmdErrorCode.FS_WRITE_SITE_DATA_FAILED]: (d) => `Failed to write site data: ${d?.error}`,

  // Author format errors
  [VmdErrorCode.AUTHOR_LIST_EMPTY]: (d) => `Author list is empty`,
  [VmdErrorCode.AUTHOR_MULTIPLE_GIT_PLACEHOLDER]: (d) => `Multiple @git placeholders found in author list (maximum 1 allowed)`,
  [VmdErrorCode.AUTHOR_INVALID_ENTRY_FORMAT]: (d) => `Invalid author format: "${d?.author}". Please use "Name->email@example.com" or "Name" or "@git"`,
  [VmdErrorCode.AUTHOR_NAME_EMPTY]: (d) => `Author name cannot be empty`,
  [VmdErrorCode.AUTHOR_DUPLICATE_EMAIL]: (d) => `Duplicate email found in author list`,
  [VmdErrorCode.AUTHOR_DUPLICATE_URL]: (d) => `Duplicate URL found in author list`,
  [VmdErrorCode.AUTHOR_INVALID_EMAIL_OR_URL]: (d) => `Invalid email or URL format`,
  [VmdErrorCode.AUTHOR_EMPTY_ENTRY]: (d) => `Author entry is empty`,
};

export class VmdError extends Error {
  public readonly code: VmdErrorCode;
  public readonly location: ErrorLocation;
  public readonly timestamp: string;
  public readonly originalError?: Error;

  constructor(
    code: VmdErrorCode,
    message: string,
    options: {
      location?: ErrorLocation;
      originalError?: Error;
    } = {}
  ) {
    super(message);
    this.name = 'VmdError';
    this.code = code;
    this.location = options.location || {};
    this.timestamp = new Date().toISOString();
    this.originalError = options.originalError;

    // This line fixes TypeScript prototype chain issues when extending Error
    Object.setPrototypeOf(this, VmdError.prototype);
  }

  public format(): string {
    const parts: string[] = [];
    parts.push(`[${this.code}] ${this.message}`);

    if (this.location.file) {
      // Ensure absolute path for clickable links
      const absolutePath = path.isAbsolute(this.location.file)
        ? this.location.file
        : path.resolve(process.cwd(), this.location.file);
      let locationStr = `  File: ${absolutePath}`;
      if (this.location.line !== undefined) {
        locationStr += `:${this.location.line}`;
        if (this.location.column !== undefined) {
          locationStr += `:${this.location.column}`;
        }
      }
      parts.push(locationStr);
      parts.push(`  URL: file://${absolutePath}`);
    }

    if (this.originalError && this.originalError !== this) {
      parts.push(`  Original: ${this.originalError.message}`);
    }

    return parts.join('\n');
  }

  public formatWithContext(fullContent?: string): string {
    const lines: string[] = [];
    lines.push('');
    lines.push(`File: ${this.location.file ? path.basename(this.location.file) : 'unknown'}`);
    lines.push('-'.repeat(70));

    if (this.location.file) {
      const absolutePath = path.isAbsolute(this.location.file)
        ? this.location.file
        : path.resolve(process.cwd(), this.location.file);
      lines.push(`Markdown source: file://${absolutePath}`);
    }

    if (this.location.line && this.location.line > 0) {
      lines.push(`Error location: line ${this.location.line}`);
    }

    lines.push('');
    lines.push(`Error message:`);
    lines.push(`  ${this.message.replace(/\n/g, '\n  ')}`);

    // Display Markdown context
    if (this.location.file && this.location.line && this.location.line > 0) {
      try {
        const content = fullContent || fs.readFileSync(this.location.file, 'utf-8');
        const fileLines = content.split('\n');
        // Show 4 lines before to 3 lines after the error line
        const startContext = Math.max(0, this.location.line - 4);
        const endContext = Math.min(fileLines.length, this.location.line + 3);

        lines.push('');
        lines.push('Markdown context:');
        lines.push('-'.repeat(70));

        for (let i = startContext; i < endContext; i++) {
          const isErrorLine = i === this.location.line - 1;
          const prefix = isErrorLine ? '>>> ' : '    ';
          const lineNum = (i + 1).toString().padStart(3);
          lines.push(`${prefix}${lineNum} | ${fileLines[i]}`);
        }

        if (endContext < fileLines.length) {
          lines.push(`    ... (${fileLines.length - endContext} more lines)`);
        }
      } catch {
        // Ignore read failures
      }
    }

    lines.push('');
    lines.push('='.repeat(70));
    return lines.join('\n');
  }

  public toJSON(): object {
    return {
      code: this.code,
      message: this.message,
      location: this.location,
      timestamp: this.timestamp,
      originalError: this.originalError?.message,
    };
  }
}

export function createVmdError(
  code: VmdErrorCode,
  details?: Record<string, any>,
  location?: ErrorLocation,
  originalError?: Error
): VmdError {
  const message = ErrorMessages[code](details);
  return new VmdError(code, message, { location, originalError });
}

export function isVmdError(error: unknown): error is VmdError {
  return error instanceof VmdError;
}

export function wrapError(
  error: unknown,
  code: VmdErrorCode = VmdErrorCode.UNKNOWN_ERROR,
  location?: ErrorLocation
): VmdError {
  if (isVmdError(error)) return error;
  if (error instanceof Error) {
    return createVmdError(code, { details: error.message }, location, error);
  }
  return createVmdError(code, { details: String(error) }, location);
}

// ============================================================================
// TYPE DEFINITIONS
// ============================================================================
//
// Core data structures:
// - FrontMatterAttributes: YAML metadata key-value pairs from markdown headers
// - ParseResult: Frontmatter parsing output with attributes, body, line count
// - NavigationNode: Site navigation tree node (section/folder/page)
// - SiteData: Site-wide metadata for frontend JSON consumption
//
// ============================================================================

export interface FrontMatterAttributes {
  [key: string]: string | undefined;
}

export interface ParseResult {
  attributes: FrontMatterAttributes;
  body: string;
  frontmatterLineCount: number;
}

export interface NavigationNode {
  title: string;
  type: 'section' | 'page' | 'folder';
  path?: string;
  hash?: string;
  hasCustomTsx?: boolean;
  mdPath?: string;
  tsxPath?: string;
  codeFiles?: { originalPath: string; hashPath: string }[];
  images?: { originalName: string; hashPath: string }[];
  tags?: string[];
  locale?: string;
  languageLinks?: Record<string, string>;
  prefixId?: string;
  children: NavigationNode[];
}

export interface SiteData {
  navigation: NavigationNode[];
  images: { originalPath: string; hashPath: string }[];
  availableLocales: string[];
  defaultLocale: string;
}

// ============================================================================
// VmdUtil CLASS
// ============================================================================
//
// Main utility class providing:
// - Error management: createError, getErrorStatus
// - Filesystem operations: fileOperation, cleanBuildOutput, resetDirectory
// - Asset processing: processImage, validateImageExists, writeCodeFile
// - Git operations: checkGitAvailable, resolveDate, resolveAuthor
// - Frontmatter parsing: parseFrontmatter, validateFrontmatter
// - Text utilities: calculateHash, cleanTitle, formatText
// - Site building: build, traverseDirectory, processMarkdownFile
// - Git sync: syncFromGit, validateDevFolderStructure
//
// ============================================================================

export class VmdUtil {
  // Project root directory
  private projectRoot: string;
  // Collected error list
  private errors: VmdError[] = [];
  // Image name to hash name mapping
  private imageMap: Record<string, string> = {};
  // Site-wide image list
  private siteImages: { originalPath: string; hashPath: string }[] = [];
  // Generated TSX file set (to avoid duplicate processing)
  private generatedTsxFiles = new Set<string>();
  // Navigation tree
  private navigation: NavigationNode[] = [];
  // Whether in remote Git mode
  private isRemoteGitMode = false;

  constructor(projectRoot: string) {
    this.projectRoot = projectRoot;
    this.isRemoteGitMode = !CONTENT_SOURCE_CONFIG.USE_LOCAL_MARKDOWN;
  }

  // ==========================================================================
  // Error Management: createError, getErrorStatus
  // ==========================================================================

  public createError(
    code: VmdErrorCode,
    details?: Record<string, any>,
    location?: ErrorLocation,
    options?: { report?: boolean; originalError?: Error }
  ): VmdError {
    const message = ErrorMessages[code](details);
    const error = new VmdError(code, message, { location, originalError: options?.originalError });
    // By default adds to error list
    if (options?.report !== false) this.errors.push(error);
    return error;
  }

  public getErrorStatus(options?: { print?: boolean; clear?: boolean }): { hasErrors: boolean; count: number; errors: VmdError[] } {
    const result = { hasErrors: this.errors.length > 0, count: this.errors.length, errors: [...this.errors] };
    if (options?.print && this.errors.length > 0) {
      this.errors.forEach(e => console.error(e.format()));
    }
    if (options?.clear) this.errors = [];
    return result;
  }

  // ==========================================================================
  // Filesystem Operations: fileOperation, cleanBuildOutput, resetDirectory, scanDirectoryForImages
  // ==========================================================================

  public fileOperation(
    operation: 'read' | 'write' | 'ensureDir',
    filePath: string,
    content?: string,
    encoding: BufferEncoding = 'utf8'
  ): string | boolean | null {
    try {
      switch (operation) {
        case 'read':
          return fs.readFileSync(filePath, encoding);
        case 'write':
          if (content === undefined) throw new Error('Write operation requires content');
          fs.writeFileSync(filePath, content);
          return true;
        case 'ensureDir':
          if (!fs.existsSync(filePath)) fs.mkdirSync(filePath, { recursive: true });
          return true;
      }
    } catch (err) {
      const code = operation === 'read' ? VmdErrorCode.FS_READ_FILE_FAILED :
                   operation === 'write' ? VmdErrorCode.FS_WRITE_FILE_FAILED :
                   VmdErrorCode.FS_CREATE_DIR_FAILED;
      this.createError(code, { file: filePath, dir: filePath, error: err instanceof Error ? err.message : String(err) }, { file: filePath });
      return operation === 'read' ? null : false;
    }
  }

  public cleanBuildOutput(): void {
    console.log('Starting build output cleanup...');
    const publicPath = path.join(this.projectRoot, BUILD_CONFIG.PUBLIC_DIR);
    const appPath = path.join(this.projectRoot, BUILD_CONFIG.APP_DIR);

    // Clean three resource directories
    [BUILD_CONFIG.VMD_CODE_DIR, BUILD_CONFIG.VMD_IMAGE_DIR, BUILD_CONFIG.VMD_JSON_DIR].forEach(dir => {
      this.resetDirectory(path.join(publicPath, dir));
    });
    // Clean page output directory
    this.resetDirectory(path.join(appPath, BUILD_CONFIG.OUT_DIR));
    console.log('Cleanup complete.');
  }

  private resetDirectory(dirPath: string): void {
    try {
      if (fs.existsSync(dirPath)) {
        fs.readdirSync(dirPath).forEach(file => {
          const filePath = path.join(dirPath, file);
          try {
            fs.rmSync(filePath, { recursive: true, force: true });
          } catch (err) {
            throw this.createError(VmdErrorCode.FS_DELETE_FILE_FAILED,
              { file: filePath, error: err instanceof Error ? err.message : String(err) }, { file: filePath }, { report: false });
          }
        });
      } else {
        fs.mkdirSync(dirPath, { recursive: true });
      }
    } catch (err) {
      if (err instanceof VmdError) throw err;
      throw this.createError(VmdErrorCode.FS_RESET_DIR_FAILED,
        { dir: dirPath, error: err instanceof Error ? err.message : String(err) }, { file: dirPath }, { report: false });
    }
  }

  public scanDirectoryForImages(dir: string): void {
    if (!fs.existsSync(dir)) return;

    fs.readdirSync(dir).forEach(item => {
      // Skip hidden files, node_modules, and excluded directories
      if (item.startsWith('.') || item === 'node_modules' || BUILD_CONFIG.EXCLUDED_DIRS.includes(item)) return;

      const srcPath = path.join(dir, item);
      const stats = fs.statSync(srcPath);

      if (stats.isDirectory()) {
        this.scanDirectoryForImages(srcPath);
      }
      // No longer process images during pre-scan, handle dynamically during rendering
    });
  }

  // ==========================================================================
  // Asset Processing: processImage, validateImageExists, writeCodeFile, processImageAndGetHash
  // ==========================================================================

  public processImage(srcPath: string): string | null {
    try {
      if (!fs.existsSync(srcPath)) {
        throw this.createError(VmdErrorCode.IMAGE_NOT_FOUND, { imagePath: srcPath }, { file: srcPath }, { report: false });
      }

      const fileBuffer = fs.readFileSync(srcPath);
      // Generate random prefix to ensure same image referenced multiple times gets different filenames
      const randomPrefix = crypto.randomUUID();
      const hash = crypto.createHash('sha256').update(randomPrefix).digest('hex');
      const ext = path.extname(srcPath).toLowerCase();
      const destFileName = `${hash}${ext}`;
      const vmdImagePath = path.join(this.projectRoot, BUILD_CONFIG.PUBLIC_DIR, BUILD_CONFIG.VMD_IMAGE_DIR);

      // Ensure target directory exists
      if (!fs.existsSync(vmdImagePath)) fs.mkdirSync(vmdImagePath, { recursive: true });

      const destPath = path.join(vmdImagePath, destFileName);
      fs.writeFileSync(destPath, fileBuffer);

      const relativeSrcPath = path.relative(this.projectRoot, srcPath);
      const relativeHashPath = path.join(BUILD_CONFIG.VMD_IMAGE_DIR, destFileName);

      // Avoid duplicate records
      if (!this.siteImages.some(img => img.hashPath === relativeHashPath)) {
        this.siteImages.push({ originalPath: relativeSrcPath, hashPath: relativeHashPath });
      }

      // Record image name to hash name mapping
      this.imageMap[path.basename(srcPath)] = destFileName;
      return hash;
    } catch (err) {
      if (err instanceof VmdError) throw err;
      throw this.createError(VmdErrorCode.IMAGE_PROCESS_FAILED,
        { imagePath: srcPath, details: err instanceof Error ? err.message : String(err) }, { file: srcPath }, { report: false });
    }
  }

  public validateImageExists(imagePath: string, location?: ErrorLocation): void {
    // Reject remote URLs
    if (imagePath.startsWith('http://') || imagePath.startsWith('https://')) {
      throw this.createError(
        VmdErrorCode.IMAGE_NOT_FOUND,
        { imageName: imagePath, reason: 'Remote images are not allowed, please use local images' },
        location,
        { report: false }
      );
    }

    // Check processed images
    const basename = path.basename(decodeURIComponent(imagePath));
    if (basename in this.imageMap) return;

    // Check possible local paths
    const decodedPath = decodeURIComponent(imagePath);
    const possiblePaths = [
      path.join(this.projectRoot, 'public', decodedPath),
      path.join(this.projectRoot, 'dev', 'assets', 'images', path.basename(decodedPath)),
      path.join(this.projectRoot, decodedPath),
      // Relative to current file's directory
      ...(location?.file ? [path.normalize(path.join(path.dirname(path.isAbsolute(location.file) ? location.file : path.join(this.projectRoot, location.file)), decodedPath))] : [])
    ];

    if (!possiblePaths.some(p => fs.existsSync(p))) {
      throw this.createError(VmdErrorCode.IMAGE_NOT_FOUND, { imageName: imagePath, searchedPaths: possiblePaths }, location, { report: false });
    }
  }

  public writeCodeFile(content: string, hash: string): void {
    const codeDir = path.join(this.projectRoot, BUILD_CONFIG.PUBLIC_DIR, BUILD_CONFIG.VMD_CODE_DIR);
    const codeFilePath = path.join(codeDir, `${hash}.txt`);

    try {
      if (!fs.existsSync(codeDir)) fs.mkdirSync(codeDir, { recursive: true });
      fs.writeFileSync(codeFilePath, content);
    } catch (err) {
      throw this.createError(VmdErrorCode.CODE_FILE_WRITE_ERROR,
        { filePath: codeFilePath, details: err instanceof Error ? err.message : String(err) }, { file: codeFilePath }, { report: false });
    }
  }

  public processImageAndGetHash(originalPath: string, currentFile?: string): string | null {
    // Possible image paths
    const possiblePaths = [
      path.join(this.projectRoot, 'dev', 'assets', 'images', originalPath),
      path.join(this.projectRoot, 'dev', 'assets', 'images', path.basename(originalPath)),
      path.join(this.projectRoot, 'public', originalPath),
      ...(currentFile ? [path.normalize(path.join(path.dirname(currentFile), originalPath))] : []),
      path.join(this.projectRoot, originalPath),
    ];

    // Find existing image file
    const srcPath = possiblePaths.find(p => fs.existsSync(p));
    if (!srcPath) return null;

    try {
      return this.processImage(srcPath);
    } catch {
      return null;
    }
  }

  public getHashedImageName(originalName: string): string | null {
    return this.imageMap[originalName] || null;
  }

  public hasImage(originalName: string): boolean {
    return originalName in this.imageMap;
  }

  public getAssetData(): { imageMap: Record<string, string>; siteImages: { originalPath: string; hashPath: string }[] } {
    return { imageMap: { ...this.imageMap }, siteImages: [...this.siteImages] };
  }

  public resetAssets(): void {
    this.imageMap = {};
    this.siteImages = [];
  }

  // ==========================================================================
  // Git Operations: checkGitAvailable, resolveDate, resolveAuthor, scanForGitPlaceholders
  // ==========================================================================

  public checkGitAvailable(shouldThrow = false): boolean {
    try {
      execSync('git --version', { stdio: 'pipe' });
      return true;
    } catch {
      if (shouldThrow) throw this.createError(VmdErrorCode.GIT_NOT_AVAILABLE, {}, undefined, { report: false });
      return false;
    }
  }

  public resolveDate(value: string, filePath: string, type: 'earliest' | 'latest'): string {
    if (value !== '@git') return value;

    try {
      const format = '%Y-%m-%d';
      // Remote mode: use .git in dev folder (downloaded repo)
      // Local mode: use .git in current working directory (v0plex project)
      const gitCwd = this.isRemoteGitMode ? path.join(this.projectRoot, 'dev') : process.cwd();

      const command = type === 'earliest'
        ? `git log --follow --format=%cd --date=format:${format} -- "${filePath}" | tail -1`
        : `git log -1 --format=%cd --date=format:${format} -- "${filePath}"`;
      const result = execSync(command, { encoding: 'utf8', cwd: gitCwd }).trim();
      if (/^\d{4}-\d{2}-\d{2}$/.test(result)) return result;
    } catch { /* Git command failed */ }

    // Return today's date on failure
    return new Date().toISOString().split('T')[0];
  }

  public resolveAuthor(value: string): string {
    if (!value.includes('@git')) return value;

    // Remote mode: use .git in dev folder (downloaded repo)
    // Local mode: use .git in current working directory (v0plex project)
    const gitCwd = this.isRemoteGitMode ? path.join(this.projectRoot, 'dev') : process.cwd();

    // Get Git user info
    let gitAuthorString = 'Unknown Author';
    try {
      const name = execSync('git config user.name', { encoding: 'utf8', stdio: 'pipe', cwd: gitCwd }).trim();
      const email = execSync('git config user.email', { encoding: 'utf8', stdio: 'pipe', cwd: gitCwd }).trim();
      if (name && email) gitAuthorString = `${name}->${email}`;
    } catch { /* Git not available */ }

    // Pure @git direct replacement
    if (value === '@git') return gitAuthorString;

    // Replace all @git placeholders
    return value.split('|').map(a => a.trim()).map(a => a === '@git' ? gitAuthorString : a).join('|');
  }

  public scanForGitPlaceholders(inputPath: string): boolean {
    const scanDir = (dirPath: string): boolean => {
      for (const item of fs.readdirSync(dirPath)) {
        const itemPath = path.join(dirPath, item);
        const stat = fs.statSync(itemPath);
        if (stat.isDirectory() && !item.startsWith('.') && item !== 'node_modules') {
          if (scanDir(itemPath)) return true;
        } else if (stat.isFile() && (item.endsWith('.md') || item.endsWith('.mdx'))) {
          if (/@git/.test(fs.readFileSync(itemPath, 'utf8'))) return true;
        }
      }
      return false;
    };

    try {
      const stats = fs.statSync(inputPath);
      if (stats.isDirectory()) return scanDir(inputPath);
      if (stats.isFile()) return /@git/.test(fs.readFileSync(inputPath, 'utf8'));
    } catch { /* Ignore errors */ }
    return false;
  }

  // ==========================================================================
  // Frontmatter Parsing: parseFrontmatter, validateFrontmatter, parseTags, hasCustomTsx
  // ==========================================================================

  public parseFrontmatter(content: string, filePath?: string): ParseResult {
    const location: ErrorLocation = filePath ? { file: filePath } : {};

    try {
      // Match frontmatter starting and ending with ---
      const match = content.match(/^---\s*[\r\n]+([\s\S]*?)[\r\n]+---/);
      if (!match) return { attributes: {}, body: content, frontmatterLineCount: 0 };

      const frontMatterBlock = match[1];
      const body = content.substring(match[0].length);
      const attributes: FrontMatterAttributes = {};

      // Simple key: value parsing
      frontMatterBlock.split('\n').forEach(line => {
        const colonIndex = line.indexOf(':');
        if (colonIndex !== -1) {
          const key = line.substring(0, colonIndex).trim();
          const value = line.substring(colonIndex + 1).trim();
          if (key) attributes[key] = value;
        }
      });

      return { attributes, body, frontmatterLineCount: match[0].split('\n').length };
    } catch (err) {
      throw this.createError(VmdErrorCode.FRONTMATTER_PARSE_ERROR,
        { details: err instanceof Error ? err.message : String(err) }, location, { report: false });
    }
  }

  public validateFrontmatter(attributes: FrontMatterAttributes, filePath: string): void {
    const required = ['title', 'created_at', 'last_updated_at', 'author', 'has_custom_tsx', 'tags'];
    const allowed = new Set(required);

    // Check required fields
    const missing = required.filter(r => !attributes[r]);
    // Check extra fields
    const extra = Object.keys(attributes).filter(k => !allowed.has(k));

    if (missing.length > 0) {
      throw this.createError(VmdErrorCode.FRONTMATTER_MISSING_REQUIRED, { fields: missing }, { file: filePath }, { report: false });
    }
    if (extra.length > 0) {
      throw this.createError(VmdErrorCode.FRONTMATTER_INVALID_FORMAT,
        { message: `Unexpected attributes: ${extra.join(', ')}. Allowed attributes: ${required.join(', ')}` }, { file: filePath }, { report: false });
    }

    // Validate has_custom_tsx value
    if (attributes.has_custom_tsx !== 'true' && attributes.has_custom_tsx !== 'false') {
      throw this.createError(VmdErrorCode.FRONTMATTER_INVALID_VALUE,
        { field: 'has_custom_tsx', value: attributes.has_custom_tsx, expected: 'true or false' }, { file: filePath }, { report: false });
    }

    // Validate date format
    const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
    const gitRegex = /^@git$/;
    ['created_at', 'last_updated_at'].forEach(field => {
      const val = attributes[field];
      if (!dateRegex.test(val!) && !gitRegex.test(val!)) {
        throw this.createError(VmdErrorCode.FRONTMATTER_INVALID_VALUE,
          { field, value: val, expected: 'YYYY-MM-DD or @git' }, { file: filePath }, { report: false });
      }
    });

    // Validate author format
    this.validateAuthorFormat(attributes.author!, filePath);
  }

  public parseTags(tagsValue: string | undefined): string[] {
    if (!tagsValue) return [];
    const match = tagsValue.match(/^\[([^\]]*)\]$/);
    return match ? match[1].split(',').map(t => t.trim()).filter(t => t.length > 0) : [];
  }

  public hasCustomTsx(attributes: FrontMatterAttributes): boolean {
    return attributes.has_custom_tsx === 'true';
  }

  private validateAuthorFormat(author: string, filePath: string): void {
    if (!author || author === '@git') return;

    const authors = author.split('|').map(a => a.trim()).filter(Boolean);
    if (authors.length === 0) {
      throw this.createError(VmdErrorCode.AUTHOR_LIST_EMPTY, {}, { file: filePath }, { report: false });
    }

    // At most one @git
    const gitCount = authors.filter(a => a === '@git').length;
    if (gitCount > 1) {
      throw this.createError(VmdErrorCode.AUTHOR_MULTIPLE_GIT_PLACEHOLDER, {}, { file: filePath }, { report: false });
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    const urlRegex = /^https?:\/\/.+/;

    for (const entry of authors) {
      if (entry === '@git') continue;

      if (entry.includes('->')) {
        const parts = entry.split('->');
        if (parts.length !== 2 || (!urlRegex.test(entry) && !emailRegex.test(parts[1].trim()))) {
          throw this.createError(VmdErrorCode.AUTHOR_INVALID_ENTRY_FORMAT, { message: entry }, { file: filePath }, { report: false });
        }
      }
    }
  }

  // ==========================================================================
  // Text and Hash Utilities: calculateHash, cleanTitle, formatText
  // ==========================================================================

  public calculateHash(content: string | Buffer, type: 'sha256' | 'path' = 'sha256'): string {
    if (type === 'path') {
      return crypto.createHash('shake256', { outputLength: 4 }).update(content).digest('hex');
    }
    return crypto.createHash('sha256').update(content).digest('hex');
  }

  public cleanTitle(name: string, isDirectory: boolean = false): string {
    let cleaned = name.replace(/^_?\d+_/, '');
    if (!isDirectory) cleaned = cleaned.replace(/\.[^/.]+$/, '');
    return cleaned.replace(/_\d+$/, '');
  }

  public formatText(text: string, options?: { escapeHtml?: boolean; capitalize?: boolean }): string {
    let result = text || '';
    if (options?.escapeHtml) {
      result = result.replace(/&/g, '&').replace(/</g, '<').replace(/>/g, '>').replace(/"/g, '"').replace(/'/g, '&#039;');
    }
    if (options?.capitalize && result) {
      result = result.charAt(0).toUpperCase() + result.slice(1);
    }
    return result;
  }

  // ==========================================================================
  // Site Building: build, traverseDirectory, processMarkdownFile, processTsxFile,
  //                generatePageComponent, buildCrossLanguageLinks, writeSiteData
  // ==========================================================================

  public build(inputPath: string, markdownCompiler: any): boolean {
    console.log(`Starting site build, input path: ${inputPath}`);
    this.errors = [];

    // Check if input path exists
    if (!fs.existsSync(inputPath)) {
      this.createError(VmdErrorCode.BUILD_INVALID_PATH, { path: inputPath }, undefined, { report: true });
      this.getErrorStatus({ print: true });
      return false;
    }

    // If @git placeholders exist, validate Git environment
    if (this.scanForGitPlaceholders(inputPath)) {
      console.log('  Validating Git environment...');
      if (!this.checkGitAvailable(true)) return false;
      console.log('  Git environment validated');
    }

    try {
      this.generatedTsxFiles.clear();
      this.navigation = [];

      const stats = fs.statSync(inputPath);
      if (stats.isDirectory()) {
        // Process directory
        if (!this.validateAndScanDirectory(inputPath)) {
          this.getErrorStatus({ print: true });
          return false;
        }
        // console.log(`[Build] Starting traverseDirectory from: ${inputPath}`);
        // console.log(`[Build] Navigation before: ${JSON.stringify(this.navigation.map(n => n.title))}`);
        this.traverseDirectory(inputPath, this.navigation, markdownCompiler);
        // console.log(`[Build] Navigation after: ${JSON.stringify(this.navigation.map(n => ({title: n.title, type: n.type, locale: n.locale})))}`);
      } else {
        // Process single file
        this.processFile(inputPath, this.navigation, markdownCompiler);
      }

      // Build cross-language links
      this.buildCrossLanguageLinks();
      // Write site data
      this.writeSiteData();

      const status = this.getErrorStatus({ print: true });
      if (status.hasErrors) {
        this.createError(VmdErrorCode.BUILD_ERROR, { details: `Build failed with ${status.count} error(s)` }, undefined, { report: true });
        return false;
      }
      return true;
    } catch (err) {
      if (err instanceof VmdError) this.errors.push(err);
      else this.createError(VmdErrorCode.BUILD_ERROR, { details: err instanceof Error ? err.message : String(err) }, { file: inputPath }, { report: true });
      this.getErrorStatus({ print: true });
      return false;
    }
  }

  private validateAndScanDirectory(inputPath: string): boolean {
    const validLocaleFolders = new Set(AVAILABLE_LANGUAGES.map(lang => lang.folder));
    const items = fs.readdirSync(inputPath);
    const subdirs = items.map(item => path.join(inputPath, item))
      .filter(itemPath => fs.statSync(itemPath).isDirectory())
      .map(itemPath => path.basename(itemPath));

    // Check for invalid language folders
    const invalidFolders = subdirs.filter(folder =>
      !validLocaleFolders.has(folder) && !BUILD_CONFIG.EXCLUDED_DIRS.includes(folder) && !folder.startsWith('.')
    );

    if (invalidFolders.length > 0) {
      this.createError(VmdErrorCode.BUILD_INVALID_LANGUAGE_FOLDER,
        { path: inputPath, invalidFolders: invalidFolders.join(', '), validFolders: Array.from(validLocaleFolders).join(', ') }, undefined, { report: true });
      return false;
    }

    // Scan images
    this.scanDirectoryForImages(inputPath);
    const assetsPath = path.join(inputPath, 'assets');
    if (fs.existsSync(assetsPath)) this.scanDirectoryForImages(assetsPath);
    return true;
  }

  private traverseDirectory(dir: string, navContainer: NavigationNode[], markdownCompiler: any, locale?: string): void {
    // console.log(`[Build] traverseDirectory called: dir=${dir}, locale=${locale || 'none'}`);
    const items = fs.readdirSync(dir);
    const validLocaleFolders = new Set(AVAILABLE_LANGUAGES.map(lang => lang.folder));
    // console.log(`[Build] Found items in ${dir}: ${items.join(', ')}`);

    // Sort by number prefix (handle both _01_ and 01_ formats)
    items.sort((a, b) => {
      const getNum = (s: string) => {
        const m = s.match(/^_?(\d+)_/);
        return m ? parseInt(m[1], 10) : null;
      };
      const numA = getNum(a), numB = getNum(b);
      if (numA !== null && numB !== null) return numA - numB;
      if (numA !== null) return -1;
      if (numB !== null) return 1;
      return a.localeCompare(b, undefined, { numeric: true });
    });
    // console.log(`[Build] Sorted items: ${items.join(', ')}`);

    items.forEach(item => {
      if (item.startsWith('.') || BUILD_CONFIG.EXCLUDED_DIRS.includes(item)) return;

      const srcPath = path.join(dir, item);
      const stats = fs.statSync(srcPath);

      if (stats.isDirectory()) {
        // Language folder - only process if it's an enabled language
        if (!locale && validLocaleFolders.has(item)) {
          // console.log(`[Build] Processing language folder: ${item}`);
          this.traverseDirectory(srcPath, navContainer, markdownCompiler, item);
        }
        // Folder with number prefix (group) - matches _01_ format
        else if (/^_(\d+)_/.test(item)) {
          // console.log(`[Build] Creating folder group: ${item} (cleaned: ${this.cleanTitle(item, true)})`);
          const newNavGroup: NavigationNode = {
            title: this.cleanTitle(item, true), type: 'folder', path: '', hash: '', hasCustomTsx: false,
            mdPath: '', tsxPath: '', codeFiles: [], images: [], tags: [], locale: locale, children: []
          };
          navContainer.push(newNavGroup);
          this.traverseDirectory(srcPath, newNavGroup.children, markdownCompiler, locale);
        }
        // Regular section (no number prefix)
        else {
          // console.log(`[Build] Creating section: ${item}`);
          const section: NavigationNode = { title: this.cleanTitle(item, true), type: 'section', locale: locale, children: [] };
          navContainer.push(section);
          this.traverseDirectory(srcPath, section.children, markdownCompiler, locale);
        }
      } else if (stats.isFile()) {
        this.processFile(srcPath, navContainer, markdownCompiler, locale);
      }
    });
  }

  private processFile(srcPath: string, navContainer: NavigationNode[], markdownCompiler: any, locale?: string): void {
    const ext = path.extname(srcPath).toLowerCase();
    if (ext === '.md' || ext === '.mdx') {
      this.processMarkdownFile(srcPath, navContainer, markdownCompiler, locale);
    } else if (ext === '.tsx' && !this.generatedTsxFiles.has(path.basename(srcPath))) {
      this.processTsxFile(srcPath, navContainer, locale);
    }
  }

  private processMarkdownFile(srcPath: string, navContainer: NavigationNode[], markdownCompiler: any, locale?: string): void {
    const ext = path.extname(srcPath).toLowerCase();
    const relativePath = path.relative(this.projectRoot, srcPath);
    const item = path.basename(srcPath);
    const location = { file: relativePath };

    console.log(`Processing MD/MDX file: ${srcPath}`);

    const mdContent = this.fileOperation('read', srcPath);
    if (typeof mdContent !== 'string') return;

    // Calculate path hash as output directory name
    const hash = this.calculateHash(relativePath, 'path');
    const pageOutDir = path.join(this.projectRoot, BUILD_CONFIG.APP_DIR, BUILD_CONFIG.OUT_DIR, hash);
    if (!this.fileOperation('ensureDir', pageOutDir)) return;

    const destFile = path.join(pageOutDir, 'page.tsx');

    try {
      const { attributes, body, frontmatterLineCount } = this.parseFrontmatter(mdContent, relativePath);
      this.validateFrontmatter(attributes, relativePath);

      const pageTitle = this.cleanTitle(item);
      const hasCustomTsx = this.hasCustomTsx(attributes);
      const tags = this.parseTags(attributes.tags);
      const createdAt = this.resolveDate(attributes.created_at as string, srcPath, 'earliest');
      const lastUpdatedAt = this.resolveDate(attributes.last_updated_at as string, srcPath, 'latest');
      const resolvedAuthor = this.resolveAuthor(attributes.author as string);

      let generatedFiles: string[] = [];
      let usedImages: { originalName: string; hashName: string }[] = [];

      if (hasCustomTsx) {
        // Use custom TSX file
        const expectedTsxPath = path.join(path.dirname(srcPath), `${path.basename(srcPath, ext)}.tsx`);
        if (!fs.existsSync(expectedTsxPath)) {
          throw this.createError(VmdErrorCode.BUILD_MISSING_CUSTOM_TSX, { expectedPath: expectedTsxPath }, location, { report: false });
        }
        this.fileOperation('write', destFile, fs.readFileSync(expectedTsxPath, 'utf8'));
        this.generatedTsxFiles.add(path.basename(expectedTsxPath));
      } else {
        // Compile Markdown
        if (!body.trim().startsWith('# ')) {
          throw this.createError(VmdErrorCode.BUILD_MISSING_H1, {}, location, { report: false });
        }

        const result = markdownCompiler.compile(body, attributes, relativePath, frontmatterLineCount);
        const tsxContent = this.generatePageComponent(
          result.html.replace(/class="/g, 'className="'),
          `${SITE_CONFIG.URL_PREFIX}/${hash}`,
          createdAt, lastUpdatedAt, resolvedAuthor
        );
        this.fileOperation('write', destFile, tsxContent);
        this.generatedTsxFiles.add(path.basename(srcPath, ext) + '.tsx');
        generatedFiles = result.generatedFiles || [];
        usedImages = result.usedImages || [];
      }

      // Add to navigation
      navContainer.push({
        title: pageTitle, type: 'page', path: `/${hash}`, hash: hash, hasCustomTsx: hasCustomTsx,
        mdPath: relativePath, tsxPath: path.relative(this.projectRoot, destFile),
        codeFiles: hasCustomTsx ? [] : generatedFiles.map(f => ({ originalPath: '', hashPath: path.join(BUILD_CONFIG.VMD_CODE_DIR, f) })),
        images: hasCustomTsx ? [] : usedImages.map(img => ({ originalName: img.originalName, hashPath: path.join(BUILD_CONFIG.VMD_IMAGE_DIR, img.hashName) })),
        tags: tags, locale: locale, children: []
      });
    } catch (err) {
      if (err instanceof VmdError) this.errors.push(err);
      else this.createError(VmdErrorCode.BUILD_ERROR, { details: err instanceof Error ? err.message : String(err) }, location, { report: true });
    }
  }

  private processTsxFile(srcPath: string, navContainer: NavigationNode[], locale?: string): void {
    const relativePath = path.relative(this.projectRoot, srcPath);
    const item = path.basename(srcPath);

    console.log(`Processing custom TSX file: ${srcPath}`);

    const content = this.fileOperation('read', srcPath);
    if (typeof content !== 'string') return;

    const hash = this.calculateHash(relativePath, 'path');
    const pageOutDir = path.join(this.projectRoot, BUILD_CONFIG.APP_DIR, BUILD_CONFIG.OUT_DIR, hash);
    if (!this.fileOperation('ensureDir', pageOutDir)) return;

    const destFile = path.join(pageOutDir, 'page.tsx');
    if (!this.fileOperation('write', destFile, content)) return;

    navContainer.push({
      title: this.cleanTitle(item), type: 'page', path: `/${hash}`, hash: hash, hasCustomTsx: true,
      mdPath: '', tsxPath: path.relative(this.projectRoot, destFile),
      codeFiles: [], images: [], tags: [], locale: locale, children: []
    });
  }

  private generatePageComponent(reactSafeHtml: string, editUrl: string, createdAt: string, lastUpdatedAt: string, author: string): string {
    const pageDatesComponent = `<PageDates publishedAt="${createdAt}" updatedAt="${lastUpdatedAt}" author="${author}" />`;
    const h1Regex = /(<H1vmd[^>]*>[\s\S]*?<\/H1vmd>)/;
    // Extract article title from H1 tag for dynamic page title
    const h1Match = reactSafeHtml.match(/<H1vmd[^>]*>([\s\S]*?)<\/H1vmd>/);
    const articleTitle = h1Match ? h1Match[1].replace(/<[^>]+>/g, '').trim() : '';
    const safeTitle = articleTitle.replace(/`/g, '\\`');
    const titleScript = articleTitle
      ? `\n  useEffect(() => {\n    document.title = \`${safeTitle} | \${SITE_TITLE_BASE}\`;\n    return () => { document.title = SITE_TITLE_BASE; };\n  }, []);`
      : '';
    // Insert date component after H1
    const contentWithMeta = h1Regex.test(reactSafeHtml)
      ? reactSafeHtml.replace(h1Regex, `$1\n${pageDatesComponent}`)
      : pageDatesComponent + '\n' + reactSafeHtml;

    return `"use client"\n\nimport React, { useEffect } from 'react';\nimport {\n  H1vmd, H2vmd, H3vmd, H4vmd, H5vmd, H6vmd,\n  Pvmd,\n  Boldvmd, Italicvmd, Bolditvmd, Strikevmd, Brvmd,\n  Ulvmd, Livmd,\n  Avmd, Imgvmd, Smallimgvmd,\n  Inlinecodevmd, Blockcodevmd,\n  Inlinemathvmd, Blockmathvmd,\n  Blockquotevmd,\n  Infovmd, Warningvmd, Successvmd, Titlevmd, Contentvmd,\n  Postvmd, Lftvmd, Rtvmd,\n  Olvmd,\n  Tablevmd, Tableheadvmd, Tablebodyvmd, Tablerowvmd, Tablecellvmd\n} from '${BUILD_CONFIG.COMPONENT_IMPORT_PATH}';\nimport { VmdThemeProvider } from '@/components/vmd/vmd-theme-context';\nimport PageDates from '@/components/common/last-updated-at';\nimport EditThisPage from '@/components/common/edit-this-page';\nimport { SITE_TITLE_BASE } from '@/config/site.config';\n\nexport default function GeneratedPage() {${titleScript}\n  return (\n    <VmdThemeProvider>\n      <div className="v0plex-content" style={{ display: 'flex', flexDirection: 'column', minHeight: '100%' }}>\n        <div className="page-typography-content" style={{ flex: 1 }}>\n${contentWithMeta}\n        </div>\n        <div style={{ marginTop: 'auto', paddingTop: '0.5rem' }}>\n          <EditThisPage url="${editUrl}" />\n        </div>\n      </div>\n    </VmdThemeProvider>\n  );\n}\n`;
  }

  private buildCrossLanguageLinks(): void {
    // Collect all pages and their prefix paths
    const collectPages = (nodes: NavigationNode[], result: Array<{ node: NavigationNode; prefixPath: string; locale: string }> = []): typeof result => {
      for (const node of nodes) {
        if (node.type === 'page' && node.mdPath) {
          // Extract number prefix from path
          const parts: string[] = [];
          node.mdPath.split(path.sep).forEach(part => {
            const match = part.match(/^_?(\d+)/);
            if (match) parts.push(match[1]);
          });
          const baseMatch = path.basename(node.mdPath).match(/^_?(\d+)/);
          if (baseMatch) {
            if (parts.length > 0 && !node.mdPath.endsWith(path.basename(node.mdPath))) parts.push(baseMatch[1]);
            result.push({ node, prefixPath: parts.join('_'), locale: node.locale || '' });
          }
        }
        if (node.children?.length) collectPages(node.children, result);
      }
      return result;
    };

    const allPages = collectPages(this.navigation);
    const pagesByPrefix = new Map<string, typeof allPages>();
    allPages.forEach(p => {
      if (!pagesByPrefix.has(p.prefixPath)) pagesByPrefix.set(p.prefixPath, []);
      pagesByPrefix.get(p.prefixPath)!.push(p);
    });

    // Build language links for each page's prefix group
    pagesByPrefix.forEach((pages, prefixPath) => {
      if (pages.length <= 1) return;
      const languageLinks: Record<string, string> = {};
      pages.forEach(({ node, locale }) => { if (locale && node.path) languageLinks[locale] = node.path; });
      pages.forEach(({ node }) => { node.languageLinks = { ...languageLinks }; node.prefixId = prefixPath; });
    });

    // Validate all configured languages exist
    const configuredLocales = new Set(AVAILABLE_LANGUAGES.map(l => l.code));
    pagesByPrefix.forEach((pages, prefixPath) => {
      const pageLocales = new Set(pages.map(p => p.locale).filter(Boolean));
      const missing = [...configuredLocales].filter(l => !pageLocales.has(l));
      if (missing.length > 0 && pages.length > 0) {
        this.createError(VmdErrorCode.BUILD_I18N_PREFIX_MISMATCH, {
          prefixPath, pageLocales: [...pageLocales].join(', '),
          missingLocales: missing.join(', '), configuredLocales: [...configuredLocales].join(', ')
        }, undefined, { report: true });
      }
    });
  }

  private writeSiteData(): void {
    const availableLocales = [...new Set(this.navigation.map(n => n.locale).filter((l): l is string => !!l))];
    const finalLocales = availableLocales.length > 0 ? availableLocales : AVAILABLE_LANGUAGES.map(l => l.code);

    const siteData: SiteData = {
      navigation: this.navigation, images: this.siteImages,
      availableLocales: finalLocales, defaultLocale: DEFAULT_LOCALE
    };

    const jsonDir = path.join(this.projectRoot, BUILD_CONFIG.PUBLIC_DIR, BUILD_CONFIG.VMD_JSON_DIR);
    this.fileOperation('ensureDir', jsonDir);
    this.fileOperation('write', path.join(jsonDir, BUILD_CONFIG.SITE_DATA_JSON), JSON.stringify(siteData, null, 2));
    // console.log(`Generated ${BUILD_CONFIG.SITE_DATA_JSON}, languages: ${finalLocales.join(', ')}`);
  }

  // ==========================================================================
  // Git Sync Operations: getGitConfig, validateGitConfig, syncFromGit,
  //                      validateRemoteDevStructure, validateDevFolderStructure, run
  // ==========================================================================

  /**
   * Remove disabled language folders from dev directory
   * This keeps the dev folder clean by deleting languages not in ENABLED_LANGUAGES
   */
  private cleanupDisabledLanguages(devFolderPath: string): void {
    const enabledLanguageFolders = new Set(AVAILABLE_LANGUAGES.map(l => l.folder));
    const supportedLanguageFolders = new Set(AVAILABLE_LANGUAGES_SUPPORT.map(l => l.folder));

    console.log(`[Git] Checking for disabled languages to cleanup...`);
    console.log(`[Git] Enabled languages: ${Array.from(enabledLanguageFolders).join(', ')}`);
    console.log(`[Git] Supported languages: ${Array.from(supportedLanguageFolders).join(', ')}`);

    const entries = fs.readdirSync(devFolderPath, { withFileTypes: true });
    const allFolders = entries.filter(e => e.isDirectory()).map(e => e.name);
    console.log(`[Git] All folders in dev: ${allFolders.join(', ')}`);

    const languageFolders = entries.filter(
      e => e.isDirectory() && supportedLanguageFolders.has(e.name)
    );
    console.log(`[Git] Language folders found: ${languageFolders.map(f => f.name).join(', ')}`);

    let removedCount = 0;
    for (const folder of languageFolders) {
      if (!enabledLanguageFolders.has(folder.name)) {
        const folderPath = path.join(devFolderPath, folder.name);
        console.log(`[Git] Removing disabled language folder: ${folder.name} at ${folderPath}`);
        try {
          fs.rmSync(folderPath, { recursive: true, force: true });
          console.log(`[Git] Successfully removed: ${folder.name}`);
          removedCount++;
        } catch (err) {
          console.warn(`[Warning] Failed to remove disabled language folder ${folder.name}: ${err instanceof Error ? err.message : String(err)}`);
        }
      } else {
        console.log(`[Git] Keeping enabled language folder: ${folder.name}`);
      }
    }

    if (removedCount > 0) {
      console.log(`[Git] Cleaned up ${removedCount} disabled language folder(s)`);
    } else {
      console.log(`[Git] No disabled language folders to clean up`);
    }
  }

  public static getGitConfig(): { repoUrl: string; branch: string } {
    return {
      repoUrl: CONTENT_SOURCE_CONFIG.GIT_CONFIG.REPO_URL,
      branch: CONTENT_SOURCE_CONFIG.GIT_CONFIG.BRANCH,
    };
  }

  public validateGitConfig(): VmdError[] {
    const errors: VmdError[] = [];
    const configPath = path.resolve(this.projectRoot, 'config/site.config.ts');
    const { REPO_URL, BRANCH } = CONTENT_SOURCE_CONFIG.GIT_CONFIG;

    // Rule 1: Non-local mode requires REPO_URL
    if (!CONTENT_SOURCE_CONFIG.USE_LOCAL_MARKDOWN && !REPO_URL) {
      errors.push(createVmdError(VmdErrorCode.CONFIG_MISSING_REPO_URL, {}, { file: configPath }));
    }

    // Local mode skips Git-related validation
    if (CONTENT_SOURCE_CONFIG.USE_LOCAL_MARKDOWN) {
      return errors;
    }

    // Rule 2: Validate branch name
    if (BRANCH && !/[\w\-./]+$/.test(BRANCH)) {
      errors.push(createVmdError(VmdErrorCode.CONFIG_INVALID_BRANCH_NAME, { branch: BRANCH }, { file: configPath }));
    }

    return errors;
  }

  public syncFromGit(): boolean {
    const errors = this.validateGitConfig();
    if (errors.length > 0) {
      errors.forEach((error, index) => {
        this.createError(VmdErrorCode.CONFIG_ERROR, { message: `${index + 1}. ${error.message}` }, undefined, { report: true });
      });
      this.createError(VmdErrorCode.CONFIG_ERROR, { message: 'Please fix configuration errors in config/site.config.ts' }, undefined, { report: true });
      return false;
    }

    // Local mode: only validate dev folder
    if (CONTENT_SOURCE_CONFIG.USE_LOCAL_MARKDOWN) {
      return this.validateDevFolderStructure();
    }

    const { REPO_URL, BRANCH } = CONTENT_SOURCE_CONFIG.GIT_CONFIG;
    const devFolderPath = path.resolve(this.projectRoot, 'dev');

    if (!REPO_URL) {
      const error = createVmdError(VmdErrorCode.CONFIG_MISSING_REPO_URL, {}, { file: 'config/site.config.ts' });
      this.errors.push(error);
      return false;
    }

    // Force check if git is available
    if (!this.checkGitAvailable(true)) {
      return false;
    }

    // Delete dev folder
    if (fs.existsSync(devFolderPath)) {
      try {
        fs.rmSync(devFolderPath, { recursive: true, force: true });
      } catch (err) {
        const error = createVmdError(
          VmdErrorCode.GIT_DELETE_FAILED,
          { message: err instanceof Error ? err.message : String(err) },
          { file: devFolderPath }
        );
        this.errors.push(error);
        return false;
      }
    }

    // Extract repo name from REPO_URL
    const repoName = (REPO_URL as string).replace(/\.git$/, '').split('/').pop() || 'repo';
    const clonedFolderPath = path.resolve(this.projectRoot, repoName);

    // Delete existing folder with same name if exists
    if (fs.existsSync(clonedFolderPath)) {
      fs.rmSync(clonedFolderPath, { recursive: true, force: true });
    }

    // Build clone command (no target path, git will use repo name as folder name)
    const cloneArgs: string[] = ['clone', '--branch', BRANCH, REPO_URL];

    // Execute full clone
    console.log(`[Git] Cloning ${BRANCH} branch from ${REPO_URL}...`);
    try {
      execSync(`git ${cloneArgs.join(' ')}`, { stdio: 'inherit', cwd: this.projectRoot });
    } catch (err) {
      const error = createVmdError(
        VmdErrorCode.GIT_CLONE_FAILED,
        { repoUrl: REPO_URL },
        undefined,
        err instanceof Error ? err : undefined
      );
      this.errors.push(error);
      // Clean up cloned folder
      if (fs.existsSync(clonedFolderPath)) {
        fs.rmSync(clonedFolderPath, { recursive: true, force: true });
      }
      return false;
    }

    // Rename to dev
    try {
      fs.renameSync(clonedFolderPath, devFolderPath);
      console.log('[Git] Renamed to dev folder');
    } catch (err) {
      this.createError(VmdErrorCode.FS_RESET_DIR_FAILED,
        { dir: clonedFolderPath, error: err instanceof Error ? err.message : String(err) }, { file: clonedFolderPath }, { report: true });
      if (fs.existsSync(clonedFolderPath)) {
        fs.rmSync(clonedFolderPath, { recursive: true, force: true });
      }
      return false;
    }

    // Clean up disabled language folders
    this.cleanupDisabledLanguages(devFolderPath);

    // Force validate remote repository directory structure
    console.log('[Git] Validating remote repository directory structure...');
    if (!this.validateRemoteDevStructure(devFolderPath)) {
      return false;
    }

    return true;
  }

  private validateRemoteDevStructure(devFolderPath: string): boolean {
    if (!fs.existsSync(devFolderPath)) {
      this.createError(VmdErrorCode.DEV_FOLDER_NOT_FOUND, {}, { file: devFolderPath }, { report: true });
      return false;
    }

    const entries = fs.readdirSync(devFolderPath, { withFileTypes: true });
    
    // All supported languages (valid language folders)
    const supportedLanguageFolders = new Set(AVAILABLE_LANGUAGES_SUPPORT.map(l => l.folder));
    // Only enabled languages are required
    const requiredLanguages = AVAILABLE_LANGUAGES.map(l => l.folder);

    // Folders that are allowed to exist alongside language folders (e.g., assets)
    const ALLOWED_NON_LANGUAGE_FOLDERS = new Set(['assets']);

    // Separate folders and files
    const folders = entries.filter(e => e.isDirectory() && !e.name.startsWith('.') && e.name !== '.git');
    const files = entries.filter(e => e.isFile());
    const folderNames = folders.map(f => f.name);

    // Check for files directly in dev root (not allowed)
    if (files.length > 0) {
      this.createError(
        VmdErrorCode.DEV_FOLDER_INVALID_STRUCTURE,
        { reason: 'Root contains files', files: files.map(f => f.name).join(', ') },
        { file: devFolderPath },
        { report: true }
      );
      return false;
    }

    // Check for invalid language folders (not in supported languages and not allowed)
    const invalidFolders = folderNames.filter(name => !supportedLanguageFolders.has(name) && !ALLOWED_NON_LANGUAGE_FOLDERS.has(name));
    if (invalidFolders.length > 0) {
      const supportedFolders = Array.from(supportedLanguageFolders);
      this.createError(
        VmdErrorCode.DEV_FOLDER_EXTRA_LANGUAGE,
        { extra: invalidFolders, allowed: supportedFolders },
        { file: devFolderPath },
        { report: true }
      );
      return false;
    }

    // Check for missing required language folders (only enabled languages)
    const missingLanguages = requiredLanguages.filter(lang => !folderNames.includes(lang));
    if (missingLanguages.length > 0) {
      this.createError(
        VmdErrorCode.DEV_FOLDER_MISSING_REQUIRED_LANGUAGE,
        { missing: missingLanguages, required: requiredLanguages },
        { file: devFolderPath },
        { report: true }
      );
      return false;
    }

    // Check each language folder has files
    for (const folder of folders) {
      const folderPath = path.join(devFolderPath, folder.name);
      if (!this.checkForFilesRecursive(folderPath)) {
        this.createError(
          VmdErrorCode.DEV_FOLDER_NO_FILES,
          { language: folder.name },
          { file: folderPath },
          { report: true }
        );
        return false;
      }
    }

    console.log(`[Git] Directory structure validated, found language folders: ${folderNames.join(', ')}`);
    return true;
  }

  public validateDevFolderStructure(): boolean {
    const devFolderPath = path.resolve(this.projectRoot, 'dev');

    if (!fs.existsSync(devFolderPath)) {
      this.createError(VmdErrorCode.DEV_FOLDER_NOT_FOUND, {}, { file: devFolderPath }, { report: true });
      return false;
    }

    const entries = fs.readdirSync(devFolderPath, { withFileTypes: true });
    const folders = entries.filter(e => e.isDirectory() && !e.name.startsWith('.'));
    const files = entries.filter(e => e.isFile());

    // Check language folders
    if (folders.length === 0) {
      this.createError(VmdErrorCode.DEV_FOLDER_NO_LANGUAGE, {}, { file: devFolderPath }, { report: true });
      return false;
    }

    // Check files
    let hasFile = files.length > 0;
    if (!hasFile) {
      for (const folder of folders) {
        const folderPath = path.join(devFolderPath, folder.name);
        if (this.checkForFilesRecursive(folderPath)) {
          hasFile = true;
          break;
        }
      }
    }

    if (!hasFile) {
      this.createError(VmdErrorCode.DEV_FOLDER_NO_FILES, {}, { file: devFolderPath }, { report: true });
      return false;
    }

    return true;
  }

  private checkForFilesRecursive(dirPath: string): boolean {
    try {
      const entries = fs.readdirSync(dirPath, { withFileTypes: true });
      for (const entry of entries) {
        if (entry.isFile()) return true;
        if (entry.isDirectory() && !entry.name.startsWith('.')) {
          if (this.checkForFilesRecursive(path.join(dirPath, entry.name))) return true;
        }
      }
    } catch {
      // Ignore errors
    }
    return false;
  }

  public validateDevFolder(devPath: string): boolean {
    if (!fs.existsSync(devPath)) {
      this.createError(VmdErrorCode.DEV_FOLDER_NOT_FOUND, {}, { file: devPath }, { report: true });
      return false;
    }

    const entries = fs.readdirSync(devPath, { withFileTypes: true });
    const folders = entries.filter(e => e.isDirectory() && !e.name.startsWith('.'));
    const files = entries.filter(e => e.isFile());

    // Get valid language folder names
    const validLanguageFolders = new Set(AVAILABLE_LANGUAGES.map(lang => lang.folder));

    // Check valid language folders
    const languageFolders = folders.filter(f => validLanguageFolders.has(f.name));
    if (languageFolders.length === 0) {
      this.createError(VmdErrorCode.DEV_FOLDER_NO_LANGUAGE, {}, { file: devPath }, { report: true });
      return false;
    }

    // Check files
    let hasFile = files.length > 0;
    if (!hasFile) {
      for (const folder of languageFolders) {
        const folderPath = path.join(devPath, folder.name);
        if (this.checkForFilesRecursive(folderPath)) {
          hasFile = true;
          break;
        }
      }
    }

    if (!hasFile) {
      this.createError(VmdErrorCode.DEV_FOLDER_NO_FILES, {}, { file: devPath }, { report: true });
      return false;
    }

    return true;
  }

  public run(inputPath: string = 'dev'): boolean {
    const fullInputPath = path.resolve(inputPath);

    // Validate or sync content
    if (CONTENT_SOURCE_CONFIG.USE_LOCAL_MARKDOWN) {
      // Local mode: validate dev folder
      if (!this.validateDevFolder(fullInputPath)) {
        return false;
      }
    } else {
      // Remote mode: sync from Git
      if (!this.syncFromGit()) {
        return false;
      }
    }

    // Clean previous build
    this.cleanBuildOutput();

    // Create Markdown compiler
    const { MarkdownCompiler } = require('./state_machine');
    const markdownCompiler = new MarkdownCompiler(this, this.projectRoot);

    // Execute build
    const success = this.build(fullInputPath, markdownCompiler);

    // Remote mode: delete dev/.git folder after build
    if (success && this.isRemoteGitMode) {
      const devGitPath = path.join(this.projectRoot, 'dev', '.git');
      if (fs.existsSync(devGitPath)) {
        try {
          fs.rmSync(devGitPath, { recursive: true, force: true });
          console.log('[Git] Deleted dev/.git folder');
        } catch (err) {
          console.warn(`[Warning] Failed to delete dev/.git folder: ${err instanceof Error ? err.message : String(err)}`);
        }
      }
    }

    return success;
  }
}

export default VmdUtil;
